### ISSUE TITLE
Search bar does not accept input containing numbers

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#100]
> Description: 
Numbers are not allowed.

> Preconditions:
The  [website](https://peviitor-ro.github.io/ui.orase/) is up and running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Write numbers as "6475645"

**Expected results** 
A message appears in the drop down with the text "Locatia nu a fost gasita!"

**Comment by AdelinaGuliman** [comment]
Numbers must not be allowed


https://github.com/peviitor-ro/ui.orase/assets/137428958/25006e40-0723-48b0-8f5b-8bc268c7862e

**Comment by OvidiuAl3x** [comment]
Fixed. Poti sa retestezi.

**Comment by ioanamariamatei** [comment]
Hello. Nu e un bug ci o propunere de enhacement.  Cand un user tasteaza o cifra/mai multe in search engine-ul Cautare Orase nu ar fi mai bine sa apara un mesaj cu textul: "Cifrele nu sunt permise/acceptate" orice? practic userul nu este lasat sa tasteze si nu are  o explicatie din partea noastra. Mersi

**Comment by OvidiuAl3x** [comment]
Am adaugat o eroare cu "Sunt permise doar litere", daca aveti alta sugestie ce sa trecem acolo puteti sa spuneti
