### ISSUE TITLE
Câmpulung La Tisa, Maramureș - is not written correctly

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/ui.orase#101]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Câmpulung La Tisa" in the search bar
3. Looking after "Câmpulung La Tisa, Maramureș"

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/c30650f9-5fc2-415d-bc7c-1f5d9e9a403a)

**Comment by OvidiuAl3x** [comment]
Fixed. Poti sa retestezi.
