### ISSUE TITLE
Vadeni from Galati - doesnt appear in the dropdown menu after searching without diacritics

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#104]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Vadeni" the search bar
Type "Vădeni" in the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
I don’t find the locality after I wrote it without diacritics
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/31e8654d-eb89-4692-b2b7-ea0a4c77fb8c)

![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/cd33ed17-254e-4e09-b943-aff4790db319)

**Comment by OvidiuAl3x** [comment]
fixed!

**Comment by SimonaNemtanu** [comment]
Closed #104 as completed
