### ISSUE TITLE
User can copy and paste parts of the location names

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#121]
> Description: 
Parts of locations can be added to the search bar by copying and pasting from another page (e.g [LEGE nr. 2 din 16 februarie 1968](https://legislatie.just.ro/Public/DetaliiDocument/189)

> Preconditions:
The  [website](https://peviitor-ro.github.io/ui.orase/) is up and running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Write a part of a location name (e.g. Poiana)

**Expected results** 
The name appears in the search bar.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Copy the other part of the location from [LEGE nr. 2 din 16 februarie 1968](https://legislatie.just.ro/Public/DetaliiDocument/189) (e.g. Vadului)

**Expected results** 
The text is copied.

**Comment by AdelinaGuliman** [comment]
> **Step 3**
Paste the other part of the location into the search bar.

**Expected results** 
The full name of the location appears in the search bar.

**Comment by AdelinaGuliman** [comment]
Expected result:
User can paste parts of the location names in the search bar

Actual result:
User cannot paste parts of the location names in the search bar.



https://github.com/peviitor-ro/ui.orase/assets/137428958/87a9f420-458f-414c-98f2-2ec0d4e8b6e7

**Comment by OvidiuAl3x** [comment]
Fixed. Poti retesta
