### ISSUE TITLE
Înfrățirea (Dolj) doesn't appear in the dropdown menu after searching without diacritics

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#125]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Infratirea" the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
I don’t find the locality after I wrote it without diacritics
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/1365967f-8907-4763-8f20-4a7511e1c54e)
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/d4d2947a-f13d-4b6f-916c-017686de8714)

**Comment by OvidiuAl3x** [comment]
Fixed. Poti retesta

**Comment by SimonaNemtanu** [comment]
Closed #125 as completed
