### ISSUE TITLE
Cernele de Sus, Dolj is missing 

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#133]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Cernele de Sus" the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
Cernele de Sus is missing

![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/1de6c3fd-32ac-4e7c-b0e7-a5ae445e9bee)
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/20143954-be52-4774-9a7d-7698808c20d8)
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/7c15abdd-6c92-43ae-8e99-073aca53d3c3)

**Comment by OvidiuAl3x** [comment]
Fixed
