### ISSUE TITLE
Izvorul Rece, Dolj is missing 

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#134]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Izvorul Rece" the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
Izvorul Rece is missing
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/52285fa2-7a83-4ad0-922e-4bbc2ac6febb)
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/59a780ce-77ed-4c5c-a02a-9613ce122262)

**Comment by OvidiuAl3x** [comment]
Fixed
