### ISSUE TITLE
Rovine, Dolj is missing 

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#135]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "Rovine" the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
Rovine from Dolj is missing
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/16a0ede7-2f6b-421d-a87e-615ea6dca940)

**Comment by OvidiuAl3x** [comment]
Fixed

**Comment by SimonaNemtanu** [comment]
Closed #135 as completed
