### ISSUE TITLE
"Motoșeni", "Bâclești", "Chetreni", "Chicerea", "Cociu", "Cornățelu", "Fântânele", "Fundătura", "Gura Crăiești", "Poiana", "Praja", "Rotăria", "Șendrești", "Țepoaia" are villages in "Motoșeni" common, "BACĂU" count

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#1353]
Description : When user is typing the villages in the search bar, the locations should appear in the dropdown menu correctly spelled and with localities information [(as in Law nr. 2 din 16 februarie 1968)](https://legislatie.just.ro/Public/DetaliiDocument/189)

Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing.

After every step delete the text you typed from the search bar.

**Comment by SimonaNemtanu** [comment]
Steps 1: Click on the search bar and write "Motoșeni"

Expected result: In the drop down menu you find "Motoșeni, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 2: Click on the search bar and write "Bâclești"

Expected result: In the drop down menu you find "Bâclești, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 3: Click on the search bar and write "Chetreni"

Expected result: In the drop down menu you find "Chetreni, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 4: Click on the search bar and write "Chicerea"

Expected result: In the drop down menu you find "Chicerea, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 5: Click on the search bar and write "Cociu"

Expected result: In the drop down menu you find "Cociu, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 6: Click on the search bar and write "Cornățelu"

Expected result: In the drop down menu you find "Cornățelu, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 6: Click on the search bar and write "Fântânele"

Expected result: In the drop down menu you find "Fântânele, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 7: Click on the search bar and write "Fundătura"

Expected result: In the drop down menu you find "Fundătura, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 9: Click on the search bar and write "Poiana"

Expected result: In the drop down menu you find "Poiana, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 10: Click on the search bar and write "Praja"

Expected result: In the drop down menu you find "Praja, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 10: Click on the search bar and write "Rotăria"

Expected result: In the drop down menu you find "Rotăria, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 11: Click on the search bar and write "Șendrești"

Expected result: In the drop down menu you find "Șendrești, Bacău (Motoșeni)"

**Comment by SimonaNemtanu** [comment]
Steps 12: Click on the search bar and write "Țepoaia"

Expected result: In the drop down menu you find "Țepoaia, Bacău (Motoșeni)"

**Comment by AdelinaGuliman** [comment]
@MarinaCosmina please report the error to @SimonaNemtanu in this form  
![Image](https://github.com/peviitor-ro/ui.orase/assets/137428958/5b7999c1-305d-42fa-834c-8e2f30e11f99)

**Comment by SimonaNemtanu** [comment]
@MarinaCosmina retest please
