### ISSUE TITLE
I.L. Caragiale, Dambovita | Search bar doesn't accept input containing punctuation marks like dot

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#136]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Type "I.L. Caragiale" the search bar

EXPECTED RESULTS:
The locality is found in the dropdown menu

ACTUAL RESULTS:
Search bar doesn't accept input containing punctuation marks like dot
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/9b389e6b-2aae-4ab8-a4c5-952ee73357db)
![image](https://github.com/peviitor-ro/ui.orase/assets/140648185/b4f79036-c101-4aad-8860-150d0e89dfae)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi

**Comment by SimonaNemtanu** [comment]
Closed #136 as completed
