### ISSUE TITLE
”Coldău”, ”Figa”, ”Rusu de Jos” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#1381]
Description: 
When user writes ”Coldău”, ”Figa”, ”Rusu de Jos” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Coldău"

**Expected results** 
The location appears in the drop-down menu as "Coldău, Bistrița-Năsăud (Beclean)"

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Figa"

**Expected results** 
The location appears in the drop-down menu as "Figa, Bistrița-Năsăud (Beclean)"

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Rusu de Jos"

**Expected results** 
The location appears in the drop-down menu as "Rusu de Jos, Bistrița-Năsăud (Beclean)"

**Comment by Cristian-Emil** [comment]
When is selected the value from the drop-box, it displayed differently than the initial text - not according to https://legislatie.just.ro/Public/DetaliiDocument/189

Step 1
request : Coldău, Bistrița-Năsăud (Beclean)
displayed : Coldău, Bistrița-Năsăud (BECLEAN)

Step 3
request : Figa, Bistrița-Năsăud (Beclean)
displayed : Figa, Bistrița-Năsăud (BECLEAN)

Step 5
request : Rusu de Jos, Bistrița-Năsăud (Beclean)
displayed :Rusu de Jos, Bistrița-Năsăud (BECLEAN)

**Comment by AdelinaGuliman** [comment]
@Cristian-Emil please assign the developer if the issue is addressed to development (@OvidiuAl3x)

**Comment by Cristian-Emil** [comment]
General bug report will be issued for all this case.
