### ISSUE TITLE
"Dealu Mare" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1388]
**Description:** 
"Dealu Mare" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Dealu Mare" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Dealu Mare, Botoșani (Dorohoi)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Dealu Mare, Botoșani (Dorohoi)"
In dropbox, the request is displayed correctly. - "Dealu Mare, Botoșani (Dorohoi)"
After you click on the text, what is displayed in the window this is different - "Dealu Mare, Botoșani (DOROHOI)"
