### ISSUE TITLE
"Bohoghina" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1393]
**Description:** 
"Bohoghina" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Bohoghina" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Bohoghina, Botoșani (Bucecea)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Bohoghina, Botoșani (Bucecea)"
In dropbox, the request is displayed correctly. - "Bohoghina, Botoșani (Bucecea)"
After you click on the text, what is displayed in the window this is different - "Bohoghina, Botoșani (BUCECEA)"
