### ISSUE TITLE
"Chițoveni" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1407]
**Description:** 
"Chițoveni" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Chițoveni, Botoșani (Flămânzi)"
In dropbox, the request is displayed correctly. - "Chițoveni, Botoșani (Flămânzi)"
After you click on the text, what is displayed in the window this is different - "Chițoveni, Botoșani (FLĂMÂNZI)"
