### ISSUE TITLE
"Chișcăreni" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1415]
**Description:** 
"Chișcăreni" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Chișcăreni, Botoșani (Săveni))"
In dropbox, the request is displayed correctly. - "Chișcăreni, Botoșani (Săveni)"
After you click on the text, what is displayed in the window this is different - "Chișcăreni, Botoșani (SĂVENI)"
