### ISSUE TITLE
"Petricani" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1416]
**Description:** 
"Petricani" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Petricani, Botoșani (Săveni)"
In dropbox, the request is displayed correctly. - "Petricani, Botoșani (Săveni)"
After you click on the text, what is displayed in the window this is different - "Petricani, Botoșani (SĂVENI)"
