### ISSUE TITLE
"Bădiuți" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1421]
**Description:** 
"Bădiuți" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Bădiuți" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Bădiuți, Botoșani (Ștefănești)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
Request - "Bădiuți, Botoșani (Ștefănești)"
In dropbox, the request is displayed correctly. - "Bădiuți, Botoșani (Ștefănești)"
After you click on the text, what is displayed in the window this is different - "Bădiuți, Botoșani (ȘTEFĂNEȘTI)"
