### ISSUE TITLE
"Albești", "Buimăceni" and "Coștiugeni" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1430]
**Description:** 
"Albești" , "Buimăceni" and "Coștiugeni" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Albești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Albești, Botoșani (Albești)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Buimăceni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Buimăceni, Botoșani (Albești)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Albești, Botoșani (Albești)"
In dropbox, the request is displayed correctly. - "Albești, Botoșani (Albești)"
After you click on the text, what is displayed in the window this is different - "Albești, BOTOȘANI (Albești)"

STEP3:
Request - "Buimăceni, Botoșani (Albești)"
In dropbox, the request is displayed correctly. - "Buimăceni, Botoșani (Albești)"
After you click on the text, what is displayed in the window this is different - "Buimăceni, BOTOȘANI (Albești)"

STEP3:
Request - "Coștiugeni, Botoșani (Albești)"
In dropbox, the request is displayed correctly. - "Coștiugeni, Botoșani (Albești)"
After you click on the text, what is displayed in the window this is different - "Coștiugeni, BOTOȘANI (Albești)"
