### ISSUE TITLE
"Ichimeni ", "Panaitoaia" , "Tudor Vladimirescu " and "Timuș" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1434]
**Description:** 

"Ichimeni ", "Panaitoaia" , "Tudor Vladimirescu " and "Timuș" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Ichimeni " in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Ichimeni , Botoșani (Avrămeni)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Panaitoaia" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Panaitoaia, Botoșani (Avrămeni)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Tudor Vladimirescu" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Tudor Vladimirescu, Botoșani (Avrămeni)".

**Comment by Florin201092** [comment]
>**Step 7**
Type "Timuș" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Timuș, Botoșani (Avrămeni)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Ichimeni , Botoșani (Avrămeni)"
In dropbox, the request is displayed correctly. - "Ichimeni , Botoșani (Avrămeni)"
After you click on the text, what is displayed in the window this is different - "Ichimeni, BOTOȘANI (Avrămeni)"

STEP3:
Request - "Panaitoaia, Botoșani (Avrămeni)"
In dropbox, the request is displayed correctly. - "Panaitoaia, Botoșani (Avrămeni)"
After you click on the text, what is displayed in the window this is different - "Panaitoaia, BOTOȘANI (Avrămeni)"

STEP5:
Request - "Tudor Vladimirescu, Botoșani (Avrămeni)"
In dropbox, the request is displayed correctly. - "Tudor Vladimirescu, Botoșani (Avrămeni)"
After you click on the text, what is displayed in the window this is different - "Tudor Vladimirescu, BOTOȘANI (Avrămeni)"

STEP7:
Request - "Timuș, Botoșani (Avrămeni)"
In dropbox, the request is displayed correctly. - "Timuș, Botoșani (Avrămeni)"
After you click on the text, what is displayed in the window this is different - "Timuș, BOTOȘANI (Avrămeni)"
