### ISSUE TITLE
"Coșuleni", "Draxini" and "Zăicești" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1437]
**Description:** 

"Coșuleni", "Draxini" and "Zăicești" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Coșuleni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Coșuleni, Botoșani (Bălușeni)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Draxini" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Draxini, Botoșani (Bălușeni)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Zăicești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Zăicești, Botoșani (Bălușeni)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Coșuleni, Botoșani (Bălușeni)"
In dropbox, the request is displayed correctly. - "Coșuleni, Botoșani (Bălușeni)"
After you click on the text, what is displayed in the window this is different - "Coșuleni, BOTOȘANI (Bălușeni)"

STEP3:
Request - "Draxini, Botoșani (Bălușeni)"
In dropbox, the request is displayed correctly. - "Draxini, Botoșani (Bălușeni)"
After you click on the text, what is displayed in the window this is different - "Draxini, BOTOȘANI (Bălușeni)"

STEP5:
Request - "Zăicești, Botoșani (Bălușeni)"
In dropbox, the request is displayed correctly. - "Zăicești, Botoșani (Bălușeni)"
After you click on the text, what is displayed in the window this is different - "Zăicești, BOTOȘANI (Bălușeni)"
