### ISSUE TITLE
"Blândești" , "Cerchejeni" and "Șoldănești" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1439]
**Description:** 
"Blândești" , "Cerchejeni" and "Șoldănești" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Blândești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Blândești, Botoșani (Blândești)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Cerchejeni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Cerchejeni, Botoșani (Blândești)".

**Comment by Florin201092** [comment]
>**Step 5**
Type "Șoldănești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Șoldănești, Botoșani (Blândești)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Blândești, Botoșani (Blândești)""
In dropbox, the request is displayed correctly. - "Coșuleni, Botoșani (Bălușeni)"
After you click on the text, what is displayed in the window this is different - "Coșuleni, BOTOȘANI (Bălușeni)"

STEP3:
Request - "Cerchejeni, Botoșani (Blândești)"
In dropbox, the request is displayed correctly. - "Cerchejeni, Botoșani (Blândești)"
After you click on the text, what is displayed in the window this is different - "Cerchejeni, BOTOȘANI (Blândești)"

STEP5:
Request - "Șoldănești, Botoșani (Blândești)"
In dropbox, the request is displayed correctly. - "Șoldănești, Botoșani (Blândești)"
After you click on the text, what is displayed in the window this is different - "Șoldănești, BOTOȘANI (Blândești)"
