### ISSUE TITLE
"Broscăuți" and "Slobozia" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1443]
**Description:** 
"Broscăuți" and "Slobozia" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Broscăuți" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Broscăuți, Botoșani".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Broscăuți" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Broscăuți, Botoșani (Broscăuți)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Slobozia" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Slobozia, Botoșani (Broscăuți)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Broscăuți, Botoșani"
In dropbox, the request is displayed correctly. - "Broscăuți, Botoșani"
After you click on the text, what is displayed in the window this is different - "Broscăuți, BOTOȘANI"

STEP3:
Request - "Broscăuți, Botoșani (Broscăuți)"
In dropbox, the request is displayed correctly. - "Broscăuți, Botoșani (Broscăuți)"
After you click on the text, what is displayed in the window this is different - "Broscăuți, BOTOȘANI (Broscăuți)"

STEP5:
Request - "Slobozia, Botoșani (Broscăuți)"
In dropbox, the request is displayed correctly. - ""Slobozia, Botoșani (Broscăuți)"
After you click on the text, what is displayed in the window this is different - "Slobozia, BOTOȘANI (Broscăuți)"
