### ISSUE TITLE
"Călărași", "Libertatea" and "Pleșani" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1448]
**Description:** 
"Călărași", "Libertatea" and "Pleșani" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Călărași" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Călărași, Botoșani (Călărași)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Libertatea" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Libertatea, Botoșani (Călărași)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Pleșani" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Pleșani, Botoșani (Călărași)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Călărași, Botoșani (Călărași)"
In dropbox, the request is displayed correctly. - "Călărași, Botoșani (Călărași)"
After you click on the text, what is displayed in the window this is different - "Călărași, BOTOȘANI (Călărași)"

STEP3:
Request - "Libertatea, Botoșani (Călărași)"
In dropbox, the request is displayed correctly. - "Libertatea, Botoșani (Călărași)"
After you click on the text, what is displayed in the window this is different - "Libertatea, BOTOȘANI (Călărași)"

STEP5:
Request - "Pleșani, Botoșani (Călărași)"
In dropbox, the request is displayed correctly. - "Pleșani, Botoșani (Călărași)"
After you click on the text, what is displayed in the window this is different - "Pleșani, BOTOȘANI (Călărași)"
