### ISSUE TITLE
"Cândești", "Călinești", "Talpa" and "Vițcani" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1452]
**Description:** 
"Cândești", "Călinești", "Talpa" and "Vițcani" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Cândești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Cândești, Botoșani (Cândești)".

**Comment by Florin201092** [comment]
>**Step 3**
Type "Călinești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Călinești, Botoșani (Cândești)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 7**
Type "Vițcani" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Vițcani, Botoșani (Cândești)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Cândești, Botoșani (Cândești)"
In dropbox, the request is displayed correctly. - "Cândești, Botoșani (Cândești)"
After you click on the text, what is displayed in the window this is different - "Cândești, BOTOȘANI (Cândești)"

STEP3:
Request - "Călinești, Botoșani (Cândești)"
In dropbox, the request is displayed correctly. - "Călinești, Botoșani (Cândești)"
After you click on the text, what is displayed in the window this is different - "Călinești, BOTOȘANI (Cândești)"

STEP5:
Request - "Talpa, Botoșani (Cândești)"
In dropbox, the request is displayed correctly. - "Talpa, Botoșani (Cândești)"
After you click on the text, what is displayed in the window this is different - "Talpa, BOTOȘANI (Cândești)"

STEP7:
Request - "Vițcani, Botoșani (Cândești)"
In dropbox, the request is displayed correctly. - "Vițcani, Botoșani (Cândești)"
After you click on the text, what is displayed in the window this is different - "Vițcani, BOTOȘANI (Cândești)"
