### ISSUE TITLE
"Concești" and "Movileni" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1456]
**Description:** 
"Concești" and "Movileni" are the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Concești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Concești, Botoșani (Concești)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Movileni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Movileni, Botoșani (Concești)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Concești, Botoșani (Concești)"
In dropbox, the request is displayed correctly. - "Concești, Botoșani (Concești)"
After you click on the text, what is displayed in the window this is different - "Concești, BOTOȘANI (Concești)"

STEP3:
Request - "Movileni, Botoșani (Concești)"
In dropbox, the request is displayed correctly. - "Movileni, Botoșani (Concești)"
After you click on the text, what is displayed in the window this is different - "Movileni, BOTOȘANI (Concești)"
