### ISSUE TITLE
”Lușca” is listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#1463]
**Description:** 
"Lușca" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
>**Step 1**
Type "Lușca" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Lușca, Bistrița-Năsăud (Năsăud)".

**Comment by AdelinaGuliman** [comment]
@Cristian-Emil you need to write a bug report to explain why the test case is FAIL

**Comment by Cristian-Emil** [comment]
General bug report will be issued for all this case.
