### ISSUE TITLE
”Budacu de Jos”, ”Buduș”, ”Jelna” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#1473]
Description: 
When user writes ”Budacu de Jos”, ”Buduș”, ”Jelna” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Budacu de Jos"

**Expected results** 
The location appears in the drop-down menu as "Budacu de Jos, Bistrița-Năsăud (Budacu de Jos)"

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Buduș"

**Expected results** 
The location appears in the drop-down menu as "Buduș, Bistrița-Năsăud (Budacu de Jos)"

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Jelna"

**Expected results** 
The location appears in the drop-down menu as "Jelna, Bistrița-Năsăud (Budacu de Jos)"

**Comment by Cristian-Emil** [comment]
Step 3  
request : Buduș, Bistrița-Năsăud (Budacu de Jos)
displayed : Buduș, Bistrița-Năsăud (Budacu De Jos)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/c79e75af-471b-4a57-89b7-9cb8fe7b8acc)

Step 5  
request : Jelna, Bistrița-Năsăud (Budacu de Jos)
displayed : Jelna, Bistrița-Năsăud (Budacu De Jos)

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/7bfd5629-887a-4d31-81e6-e22a67e45c68)

**Comment by Cristian-Emil** [comment]
Teasted 10.04.2024 :
Displayed - Sat Buduș, BISTRIȚA-NĂSĂUD (Budacu de Jos)
