### ISSUE TITLE
”Monariu”, ”Simionești” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#1474]
Description: 
When user writes ”Monariu”, ”Simionești” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Monariu"

**Expected results** 
The location appears in the drop-down menu as "Monariu, Bistrița-Năsăud (Budacu de Jos)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Simionești"

**Expected results** 
The location appears in the drop-down menu as "Simionești, Bistrița-Năsăud (Budacu de Jos)".

**Comment by Cristian-Emil** [comment]
When is selected the value from the drop-box, it displayed differently than the initial text - not according to https://legislatie.just.ro/Public/DetaliiDocument/189

Step 1
request : Monariu, Bistrița-Năsăud (Budacu de Jos)
displayed : Monariu, Bistrița-Năsăud (Budacu De Jos)
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/c62905e1-1d05-4505-9fbc-a185af168381)

Step 3
request : Simionești, Bistrița-Năsăud (Budacu de Jos)
displayed : Simionești, Bistrița-Năsăud (Budacu De Jos)
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/3c49931a-19eb-44cb-8e51-28c0cf168845)

**Comment by Cristian-Emil** [comment]
General bug report will be issued for all this case.

**Comment by Cristian-Emil** [comment]
Tested 01.04.2024 - test PASS:
Correc t displayed : Sat Simionești, BISTRIȚA-NĂSĂUD (Budacu de Jos)
