### ISSUE TITLE
"Cordăreni", "Grivița" and "Slobozia" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1507]
**Description:** 
"Cordăreni", "Grivița" and "Slobozia" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Cordăreni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Cordăreni, Botoșani (Cordăreni)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Grivița" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Grivița, Botoșani (Cordăreni)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Slobozia" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Slobozia, Botoșani (Cordăreni)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Cordăreni, Botoșani (Cordăreni)"
In dropbox, the request is displayed correctly. - "Cordăreni, Botoșani (Cordăreni)"
After you click on the text, what is displayed in the window this is different - "Cordăreni, BOTOȘANI (Cordăreni)"

STEP3:
Request - "Grivița, Botoșani (Cordăreni)"
In dropbox, the request is displayed correctly. - "Grivița, Botoșani (Cordăreni)"
After you click on the text, what is displayed in the window this is different - "Grivița, BOTOȘANI (Cordăreni)"

STEP5:
Request - "Slobozia, Botoșani (Cordăreni)"
In dropbox, the request is displayed correctly. - "Slobozia, Botoșani (Cordăreni)"
After you click on the text, what is displayed in the window this is different - "Slobozia, BOTOȘANI (Cordăreni)"
