### ISSUE TITLE
"Corlăteni", "Carasa", "Podeni" and "Vlădeni" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1509]
**Description:** 
"Corlăteni", "Carasa", "Podeni" and "Vlădeni" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Corlăteni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Corlăteni, Botoșani (Corlăteni)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Carasa" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Carasa, Botoșani (Corlăteni)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Podeni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Podeni, Botoșani (Corlăteni)".

**Comment by Florin201092** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 7**
Type "Vlădeni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Vlădeni, Botoșani (Corlăteni)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Corlăteni, Botoșani (Corlăteni)"
In dropbox, the request is displayed correctly. - "Corlăteni, Botoșani (Corlăteni)"
After you click on the text, what is displayed in the window this is different - "Corlăteni, BOTOȘANI (Corlăteni)"

STEP3:
Request - "Carasa, Botoșani (Corlăteni)"
In dropbox, the request is displayed correctly. - "Carasa, Botoșani (Corlăteni)"
After you click on the text, what is displayed in the window this is different - "Carasa, BOTOȘANI (Corlăteni)"

STEP5:
Request - "Podeni, Botoșani (Corlăteni)"
In dropbox, the request is displayed correctly. - "Podeni, Botoșani (Corlăteni)"
After you click on the text, what is displayed in the window this is different - "Podeni, BOTOȘANI (Corlăteni)"

STEP7:
Request - "Vlădeni, Botoșani (Corlăteni)"
In dropbox, the request is displayed correctly. - "Vlădeni, Botoșani (Corlăteni)"
After you click on the text, what is displayed in the window this is different - "Vlădeni, BOTOȘANI (Corlăteni)"
