### ISSUE TITLE
"Corni", "Balta Arsă", "Mesteacăn" and "Sarafinești" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1511]
**Description:** 
"Corni", "Balta Arsă", "Mesteacăn" and "Sarafinești" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Corni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Corni, Botoșani (Corni)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Balta Arsă" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Balta Arsă, Botoșani (Corni)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Mesteacăn" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Mesteacăn, Botoșani (Corni)".

**Comment by Florin201092** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Sarafinești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Sarafinești, Botoșani (Corni)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Corni, Botoșani (Corni)"
In dropbox, the request is displayed correctly. - "Corni, Botoșani (Corni)"
After you click on the text, what is displayed in the window this is different - "Corni, BOTOȘANI (Corni)"

STEP3:
Request - "Balta Arsă, Botoșani (Corni)"
In dropbox, the request is displayed correctly. - "Balta Arsă, Botoșani (Corni)"
After you click on the text, what is displayed in the window this is different - "Balta Arsă, BOTOȘANI (Corni)"

STEP5:
Request - "Mesteacăn, Botoșani (Corni)"
In dropbox, the request is displayed correctly. - "Mesteacăn, Botoșani (Corni)"
After you click on the text, what is displayed in the window this is different - "Mesteacăn, BOTOȘANI (Corni)"

STEP7:
Request - "Sarafinești, Botoșani (Corni)"
In dropbox, the request is displayed correctly. - "Sarafinești, Botoșani (Corni)"
After you click on the text, what is displayed in the window this is different - "Sarafinești, BOTOȘANI (Corni)"
