### ISSUE TITLE
"Coșula", "Buda", "Pădureni" and "Șupitca" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Florin201092** [peviitor-ro/ui.orase#1513]
**Description:** 
"Coșula", "Buda", "Pădureni" and "Șupitca" are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Florin201092** [comment]
>**Step 1**
Type "Coșula" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Coșula, Botoșani (Coșula)".

**Comment by Florin201092** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 3**
Type "Buda" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Buda, Botoșani (Coșula)".

**Comment by Florin201092** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 5**
Type "Pădureni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Pădureni, Botoșani (Coșula)".

**Comment by Florin201092** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Florin201092** [comment]
>**Step 7**
Type "Șupitca" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Șupitca, Botoșani (Coșula)".

**Comment by Cristian-Emil** [comment]
ATTENTION:
STEP1:
Request - "Coșula, Botoșani (Coșula)"
In dropbox, the request is displayed correctly. - "Coșula, Botoșani (Coșula)"
After you click on the text, what is displayed in the window this is different - "Coșula, BOTOȘANI (Coșula)"

STEP3:
Request - "Buda, Botoșani (Coșula)"
In dropbox, the request is displayed correctly. - "Buda, Botoșani (Coșula)"
After you click on the text, what is displayed in the window this is different - "Buda, BOTOȘANI (Coșula)"

STEP5:
Request - "Pădureni, Botoșani (Coșula)"
In dropbox, the request is displayed correctly. - "Pădureni, Botoșani (Coșula)"
After you click on the text, what is displayed in the window this is different - "Pădureni, BOTOȘANI (Coșula)"

STEP7:
Request - "Șupitca, Botoșani (Coșula)"
In dropbox, the request is displayed correctly. - "Șupitca, Botoșani (Coșula)"
After you click on the text, what is displayed in the window this is different - "Șupitca, BOTOȘANI (Coșula)"
