### ISSUE TITLE
”Milaș”, ”Comlod”, ”După Deal” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#1620]
Description: 
When user writes ”Milaș”, ”Comlod”, ”După Deal” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Milaș"

**Expected results** 
The location appears in the drop-down menu as "Milaș, Bistrița-Năsăud (Milaș)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Comlod"

**Expected results** 
The location appears in the drop-down menu as "Comlod, Bistrița-Năsăud (Milaș)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "După Deal"

**Expected results** 
The location appears in the drop-down menu as "După Deal, Bistrița-Năsăud (Milaș)".

**Comment by AdelinaGuliman** [comment]
After running the test please put the label PASS and remove it to PASS Status

**Comment by AdinaIT** [comment]
Done
