### ISSUE TITLE
The first 3 letters you typed in the search bar bring a relevant result

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#19]
> Description: 
The first 3 letters written in the search bar brings relevant results.

> Preconditions:
The website is up and running.
The database contains valid information.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click on the search bar.

**Expected results** 
The search bar is activated.

**Comment by AdelinaGuliman** [comment]
> **Step 2**
Write 3 letters.

**Expected results** 
Localities associated with those letters appear in the drop down

**Comment by AdelinaGuliman** [comment]
**Actual results** 
Cities that start with the typed letters do not have priority in the drop-down menu


<img width="594" alt="Screenshot at Feb 01 14-50-23" src="https://github.com/peviitor-ro/ui.orase/assets/137428958/ea61ba13-2f98-4273-869b-db43bcd1fafe">
<img width="517" alt="Screenshot at Feb 01 14-51-50" src="https://github.com/peviitor-ro/ui.orase/assets/137428958/c33b968e-c841-4332-a84c-8fa6b48249dd">

**Comment by OvidiuAl3x** [comment]
Poti sa retestezi, acum le afiseaza in ordine alfabetica
