### ISSUE TITLE
"Căbești, Goila, Gurbești, Josani, Sohodol" are villages in "Căbești" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#2063]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Comment by chiparca81** [comment]
**Precondition**

The website is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Căbești"

**Expected result**

In the drop down menu you find "Căbești, BIHOR(Căbești)"

**Test Data**

Căbești

**Comment by chiparca81** [comment]
**Steps 3**

Write "Gurbești"

**Expected result**

In the drop down menu you find "Gurbești, BIHOR(Căbești)"

**Test Data**

Gurbești

**Comment by chiparca81** [comment]
**Steps 4**

Write "Josani"

**Expected result**

In the drop down menu you find "Josani, BIHOR(Căbești)"

**Test Data**

Josani

**Comment by chiparca81** [comment]
**Steps 5**

Write "Sohodol"

**Expected result**

In the drop down menu you find "Sohodol, BIHOR(Căbești)"

**Test Data**

Sohodol

**Comment by AdinaIT** [comment]
Environment: Run Tests
Browser: Chrom
Device: Laptop
OS: Windows 10

Steps to reproduce:

1 Open the @Adelina Guliman Test case ui.orase 
2. Check TC :  "Căbești, Goila, Gurbești, Josani, Sohodol" are villages in "Căbești" commune, "BIHOR" county
[#2063](https://github.com/peviitor-ro/ui.orase/issues/2063)

Expected results:
Website link is up and running.

Actual result:
Missing Precondition:
The [website] it isn't up and running, missing link!



![Image](https://github.com/peviitor-ro/ui.orase/assets/127322865/62d0a810-5437-478a-a22e-36399e4061c5)

**Comment by chiparca81** [comment]
Adina, ce s-a schimbat este faptul ca acum in tool apre in fata mentiunea de "sat, oras, municipiu"!

**Comment by AdelinaGuliman** [comment]
@AdinaIT please retest
