### ISSUE TITLE
Santuhalm, Hunedoara (Deva) - has an extra space after the name of the locality

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#27]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Sântuhalm" in the search bar

EXPECTED RESULTS:
The name is written corect: Sântuhalm, Hunedoara (Deva)

ACTUAL RESULTS:
The name isn't wirtten corect: Sântuhalm, Hunedoara (Deva) - has an extra space after the name of the locality

![7](https://github.com/peviitor-ro/ui.orase/assets/143128512/7d1d159d-1e62-4361-ab6f-7fceeea47b5b)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
