### ISSUE TITLE
"Roșia de Secaș" is listed in the dropdown menu when searched

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#277]
Description : When user is typing "Roșia de Secaș " in the search bar, the location should appear in the dropdown menu correctly spelled and with locality information (as in Law nr. 2 din 16 februarie 1968)

**Preconditions :** the website (https://peviitor-ro.github.io/ui.orase/) is up and runing.

**Comment by DeedeeDL** [comment]
** Step 1 :** Type "Roșia de Secașă" in the search bar . Expected result : "Sălciua" is listed as an option in the dropdown menu, and appears as "Roșia Montană, Alba"

Expected result : "Roșia de Secașă" is listed as an option in the dropdown menu, and appears as "Roșia Montană, Alba"

**Comment by AndraADM** [comment]
environment: test
browser: Opera
Device: laptop
OS: Windows 10

Steps to reproduce:
1.Open the [website](https://peviitor-ro.github.io/ui.orase/)
2. Type in the search bar "Roșia de Secașă"

Expected results:
1. "Roșia de Secașă" is shown in the dropdown menu

Actual results:
1.  "Roșia de Secașă" is not found in the dropdown menu



![Image](https://github.com/peviitor-ro/ui.orase/assets/142739627/9ad701cf-d31c-49b3-bc50-29d24011b992)




But if we type "Roșia de Secaș" in the search bar, in the dropdown menu is shown  "Roșia de Secaș, Alba"


![Image](https://github.com/peviitor-ro/ui.orase/assets/142739627/8b70a802-a648-45be-8fec-02ba1e3b514a)

**Comment by DeedeeDL** [comment]
Problem solved. Now retest and pass if it's correct
