### ISSUE TITLE
”Valea Bistrei”, ”Voislova”, ”23 August” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#2819]
Description: 
When user writes ”Valea Bistrei”, ”Voislova”, ”23 August” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Valea Bistrei"

**Expected results** 
The location appears in the drop-down menu as "Sat Valea Bistrei, CARAȘ-SEVERIN(Zăvoi)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Voislova"

**Expected results** 
The location appears in the drop-down menu as "Sat Voislova, CARAȘ-SEVERIN(Zăvoi)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "23 August"

**Expected results** 
The location appears in the drop-down menu as "Sat 23 August, CARAȘ-SEVERIN(Zăvoi)".

**Comment by MaGiCo19** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser
Write in the search bar "23 August"

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat 23 August, CARAȘ-SEVERIN(Zăvoi)"

ACTUAL RESULTS:
1. When typing "23 August" it appears that the search bar doesn't accept inputs containing numbers.
2. When typing ”August” the location appears as "Sat 23 August, CARAȘ-SEVERIN(Zăvoi)"
 


![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/c0d02872-407c-4056-a980-e5b2c27fd826)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/1aa5bdd4-68e1-426e-beab-747590177a17)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/626651a1-36e6-460e-99c6-52366b2e23a6)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
