### ISSUE TITLE
"MEDGIDIA", "Remus Opreanu" , "Valea Dacilor" is listed in the drop-down menu

### ISSUE THREAD

**Issue by AndraADM** [peviitor-ro/ui.orase#2843]
Description: 
When user writes "MEDGIDIA", "Remus Opreanu" , "Valea Dacilor" the location appears in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AndraADM** [comment]
> **Step 1**
Write in the search bar "Medgidia"

**Expected results** 
The location appears in the drop-down menu as "Oras MEDGIDIA, CONSTANȚA, (MEDGIDIA)"

**Comment by AndraADM** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by AndraADM** [comment]
> **Step 3**
Write in the search bar "Remus Opreanu"

**Expected results** 
The location appears in the drop-down menu as "Sat Remus Opreanu, CONSTANȚA, (MEDGIDIA)"

**Comment by AndraADM** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by AndraADM** [comment]
> **Step 3**
Write in the search bar "Valea Dacilor"

**Expected results** 
The location appears in the drop-down menu as "Sat Valea Dacilor, CONSTANȚA, (MEDGIDIA)"

**Comment by MaGiCo19** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser https://peviitor-ro.github.io/ui.orase/
Write in the search bar "MEDGIDIA"


EXPECTED RESULTS:
The location appears in the drop-down menu as "Oras MEDGIDIA, CONSTANȚA, (MEDGIDIA)"

ACTUAL RESULTS:
-After searching MEDGIDIA there are 2 results shown: 1. ” MUNICIPIUL MEDGIDIA, CONSTANTA” and 2. "Oras MEDGIDIA, CONSTANȚA, (MEDGIDIA)". 
- The Law no.2 from 1968 on Administrative Organisation of the Romanian Teritory stipulates that MEDGIGIA is ”Municipiu” and not ”Oras”.



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/7177608a-7ef8-470d-84eb-1f6e6f4daca3)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/75235855-8942-4eab-8f5f-a9ca21c47a14)
