### ISSUE TITLE
Dâlja Mare, Hunedoara (Petroșani) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#29]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser 
2. Type "Dâlja Mare" in the search bar

EXPECTED RESULTS:
The full name is visible in the search bar - Dâlja Mare, Hunedoara (Petroșani)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![10](https://github.com/peviitor-ro/ui.orase/assets/143128512/84d0eec4-10bf-43df-8316-b140ed5c8f56)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
