### ISSUE TITLE
BOTOSANI-BOZIENI, ESANCA, LISMANITA, BAJURA, BADIUT, BOBULESTI - extraspace between the name of the village and coma

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#32]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: pc
OS: Windows 10

**STEPS TO REPRODUCE:**

Open URL in browser
Type "BOZIENI in the search bar
Type "ESANCA" the search bar
Type "LISMANITA" in the search bar
Type "BAJURA" in the search bar
Type "BADIUT" in the search bar
Type "BOBULESTI" in the search bar

**EXPECTED RESULTS:**
All of the villages are  spelled correctly.

**ACTUAL RESULTS:**
There are some extraspace between the name of the village and coma.

<img width="394" alt="BADIUTI,BOTOSANI - EXTRASPACE" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/489354f5-2746-4097-b1b1-bdf50d3a46d4">
<img width="423" alt="BODEASA,BOTOSANI - EXTRASPACE" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/5fda159f-226e-45ad-b033-c8b79f73bd6d">
<img width="423" alt="BOZIENI,BOTOSANI - EXTRASPACE" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/7c6f2fb6-e07e-46cd-b3dd-f9197354c43d">
<img width="394" alt="ESANCA,BOTOSANI, EXTRASPACE" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/92737fb4-2f21-4b38-8ee1-22272cfbd314">
<img width="423" alt="LISMANITA,BOTOSANI - EXTRASPACE" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/903f4afe-e818-4518-9b94-57ebfd80461e">

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by DeedeeDL** [comment]
Retested, pass
