### ISSUE TITLE
"Finiș, Brusturi, Fiziș, Ioaniș, Șuncuiș" are villages in "Finiș" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#3236]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Comment by chiparca81** [comment]
**Precondition**

The website is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Finiș"

**Expected result**

In the drop down menu you find "Finiș, BIHOR(Finiș)"

**Test Data**

Finiș

**Comment by chiparca81** [comment]
**Steps 2**

Write "Brusturi"

**Expected result**

In the drop down menu you find "Brusturi, BIHOR(Finiș)"

**Test Data**

Brusturi

**Comment by chiparca81** [comment]
**Steps 3**

Write "Fiziș"

**Expected result**

In the drop down menu you find "Fiziș, BIHOR(Finiș)"

**Test Data**

Fiziș

**Comment by chiparca81** [comment]
**Steps 4**

Write "Ioaniș"

**Expected result**

In the drop down menu you find "Ioaniș, BIHOR(Finiș)"

**Test Data**

Ioaniș

**Comment by chiparca81** [comment]
**Steps 5**

Write "Șuncuiș"

**Expected result**

In the drop down menu you find "Șuncuiș, BIHOR(Finiș)"

**Test Data**

Șuncuiș

**Comment by TaniaR33** [comment]
La descriere ai uitat sa pui link-ul catre site-ul cu localitati:
https://peviitor-ro.github.io/ui.orase/
