### ISSUE TITLE
Boș, Hunedoara (Hunedoara) - Location not found when I write with diacritics

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#33]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:
1. Open URL in browser
2. Type "Boș" in the search bar (with diacritics)

EXPECTED RESULTS:
1. The drop-down items starting with "Boș" are visible
2. I can choose the locality from the list: Boș, Hunedoara (Hunedoara)

ACTUAL RESULTS:
1. The drop-down items starting with "Boș" are not visible
2. I can not choose the locality from the list: Boș, Hunedoara (Hunedoara)

![11](https://github.com/peviitor-ro/ui.orase/assets/143128512/20ce215a-f903-4b22-a33d-17370c89af27)

![12](https://github.com/peviitor-ro/ui.orase/assets/143128512/31c39861-fff1-4c51-a571-84d8ae41cf24)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
