### ISSUE TITLE
Verify if  "ARAD"  it is a county in Romania

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#330]
**Descriptions**

When you click on the search bar "ARAD" appears in the list of counties in the drop down menu.

**Comment by chiparca81** [comment]
Steps 1

Click on search bar.

Expected result

"Arad" is displayed in the drop-down menu with the list of counties

**Comment by Florin201092** [comment]
@chiparca81 
Note with correct format for Step 2:

**Step 2**
Type "Arad" in the search bar.

Expected results
The location is listed in the drop-down menu as "Arad, Arad".

**Comment by Florin201092** [comment]
I made a mistake, everything is correct.
