### ISSUE TITLE
Streisângeorgiu, Hunedoara (Călan) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#34]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Streisângeorgiu" in the search bar
3. Select Streisângeorgiu, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar - Streisângeorgiu, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![13](https://github.com/peviitor-ro/ui.orase/assets/143128512/95f5392a-f4bf-4a1c-87b6-57edee3773a0)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
