### ISSUE TITLE
"23 August" is listed in the drop-down menu

### ISSUE THREAD

**Issue by AndraADM** [peviitor-ro/ui.orase#3423]
Description: 
When user writes "23 August" the location appears in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AndraADM** [comment]
> **Step 1**
Write in the search bar "23 August"

**Expected results** 
The location appears in the drop-down menu as "Comuna 23 August, CONSTANȚA"

**Comment by Catalinay** [comment]
ENVIROMENT: production
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:
1) Open ### [URL](https://peviitor-ro.github.io/ui.orase/) in browser
2) Type "23 August" in the search bar
3) The search drop-down menu will open
4) Check the name of the city written in the search bar



![Image](https://github.com/peviitor-ro/ui.orase/assets/161432647/cfec9f50-990d-4cbd-b8a6-e7bb6e8c9728)





EXPECTED RESULTS:
The location is written in the search bar as "23 August".


ACTUAL RESULTS:
The location is written in the search bar as "August". Can`t type any numbers.

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
