### ISSUE TITLE
Nădăștia De Jos, Hunedoara (Călan) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#35]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Nădăștia De Jos" in the search bar
3. Select Nădăștia De Jos, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar - Nădăștia De Jos, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![14](https://github.com/peviitor-ro/ui.orase/assets/143128512/7c9e9202-e0e3-4923-acc8-cb454940f13c)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
