### ISSUE TITLE
”Sântuhalm”, ”Archia”, ”Bârcea Mică”, ”Cristur” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#3523]
Description: 
When user writes ”Sântuhalm”, ”Archia”, ”Bârcea Mică”, ”Cristur” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Sântuhalm"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Sântuhalm, HUNEDOARA (DEVA)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Archia"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Archia, HUNEDOARA (DEVA)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Bârcea Mică"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Bârcea Mică, HUNEDOARA (DEVA)".

**Comment by bogi1492** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 7**
Write in the search bar "Cristur"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Cristur, HUNEDOARA (DEVA)".

**Comment by MaGiCo19** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Write in the search bar "Bârcea Mică"

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Bârcea Mică, HUNEDOARA (DEVA)"

ACTUAL RESULTS:
"Sat Bârcea Mică, HUNEDOARA (DEVA)" is missing


![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/37618d14-1b3e-4f56-90ce-2275adef08d9)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/1adbfbac-f36e-48cb-a99b-c5a7b6f88429)

**Comment by MaGiCo19** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Write in the search bar "Cristur"

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Cristur, HUNEDOARA (DEVA)"

ACTUAL RESULTS:
"Sat Cristur, HUNEDOARA (DEVA)" is missing


![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/b925c5c5-ca52-466b-89ab-5898e445dcf1)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/49a945d5-99d8-4af2-bd66-a3550c9ad70f)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
