### ISSUE TITLE
”Mesteacăn”, ”Potingani”, ”Ruda-Brad”, ”Țărățel”, ”Valea Bradului” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#3527]
Description: 
When user writes ”Mesteacăn”, ”Potingani”, ”Ruda-Brad”, ”Țărățel”, ”Valea Bradului” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Mesteacăn"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Mesteacăn, HUNEDOARA (BRAD)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Potingani"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Potingani, HUNEDOARA (BRAD)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Ruda-Brad"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Ruda-Brad, HUNEDOARA (BRAD)".

**Comment by bogi1492** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 7**
Write in the search bar "Țărățel"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Țărățel, HUNEDOARA (BRAD)".

**Comment by bogi1492** [comment]
> **Step 8**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 9**
Write in the search bar "Valea Bradului"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Valea Bradului, HUNEDOARA (BRAD)".

**Comment by MaGiCo19** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Write in the search bar "Valea Bradului"

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Valea Bradului, HUNEDOARA (BRAD)"

ACTUAL RESULTS:
"Sat Valea Bradului, HUNEDOARA (BRAD)" is missing

![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/6e073711-43e7-48b2-a837-bc41f25b2eb9)




![Image](https://github.com/peviitor-ro/ui.orase/assets/150843617/26fe33f3-437a-4f03-871d-ab47c50bca3a)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
