### ISSUE TITLE
”Răcăștia”, ”Boș”, ”Groș”, ”Hășdat”, ”Peștișu Mare” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#3530]
Description: 
When user writes ”Răcăștia”, ”Boș”, ”Groș”, ”Hășdat”, ”Peștișu Mare” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Răcăștia"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Răcăștia, HUNEDOARA (HUNEDOARA)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Boș"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Boș, HUNEDOARA (HUNEDOARA)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Groș"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Groș, HUNEDOARA (HUNEDOARA)".

**Comment by bogi1492** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 7**
Write in the search bar "Hășdat"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Hășdat, HUNEDOARA (HUNEDOARA)".

**Comment by bogi1492** [comment]
> **Step 8**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 9**
Write in the search bar "Peștișu Mare"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Peștișu Mare, HUNEDOARA (HUNEDOARA)".

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
