### ISSUE TITLE
”URICANI” is listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#3571]
**Description:** 
"URICANI" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by ElenaBlejan** [comment]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10 

STEPS TO REPRODUCE:
1.Open URL in browser
2. Check TC : "”URICANI” is listed in the drop-down menu
#3571

EXPECTED RESULT:
Steps to reproduce the test case are listed.

ACTUAL RESULT:
Steps to reproduce the test case are missing.

**Comment by bogi1492** [comment]
>**Step 1**
Type "IAȘI" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Oraș** URICANI, **HUNEDOARA**".
