### ISSUE TITLE
Nădăștia De Sus, Hunedoara (Călan) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#37]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Nădăștia De Sus" in the search bar
3. Select Nădăștia De Sus, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar - Nădăștia De Jos, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![16](https://github.com/peviitor-ro/ui.orase/assets/143128512/a2e25007-ff90-46ff-8454-684610a38b22)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
