### ISSUE TITLE
"Mocrea" it is a village in "INEU" locality, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#371]
Steps 1

Acces to the link https://peviitor-ro.github.io/ui.orase/

Expected result

The page is opens

**Comment by CristinaVoicu** [comment]
Missing steps for verifying the location from the title.

**Comment by chiparca81** [comment]
**Steps 2**

Write "INEU"

**Expected result**

In the drop down menu you find "INEU, BIHOR(INEU)"

** Test data**

  INEU
