### ISSUE TITLE
Nădăștia De Sus, Hunedoara (Călan) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#38]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Nădăștia de Sus" in the search bar
3. Select Nădăștia de Sus, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![16](https://github.com/peviitor-ro/ui.orase/assets/143128512/c3098467-1ec5-4043-b6bb-035121cdf660)
![17](https://github.com/peviitor-ro/ui.orase/assets/143128512/065aa450-0f5b-46b4-b1b0-de355fd9246c)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
