### ISSUE TITLE
"Crasna" is listed in the drop-down menu

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/ui.orase#3890]
**Description:** 
"Crasna" is listed in the drop-down menu alongside its corresponding county, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by iBixee** [comment]
>**Step 1**
Type "Crasna" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "** Comuna** Crasna, GORJ".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 3890
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : "Crasna" is listed in the drop-down menu
[#3890](https://github.com/peviitor-ro/ui.orase/issues/3890)

Expected results (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :  "Comuna Crasna, GORJ" - see below screenshot
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/7e0a1049-7abc-4c27-8b8f-400c8b95a1f2)

Actual result :
In STEP 3 request is displayed with double asterixes "**Comuna** Crasna, DOLJ " - see below screenshot
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/fc519430-ed26-4066-b518-ba10b61bb060)
