### ISSUE TITLE
Ohaba Streiului, Hunedoara (Călan) - The full name is not visible in the search bar 

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#39]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Ohaba Streiului" in the search bar
3. Select Ohaba Streiului, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar - Ohaba Streiului, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![18](https://github.com/peviitor-ro/ui.orase/assets/143128512/c8941ef9-3cfe-41d8-81f6-9c349ac2a017)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
