### ISSUE TITLE
"Glob" is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#399]
Description: 
When user writes "Glob" the location appears in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Write in the search bar "Glob"

**Expected results** 
The location appears in the drop-down menu as "Glob, Alba (Almașu Mare)"

**Comment by AdinaIT** [comment]
Environment: Run Tests
Browser: Chrom
Device: Laptop
OS: Windows 10

Steps to reproduce:

1 Open the https://peviitor-ro.github.io/ui.orase/
2. Type in the search bar "_Glob_"

Expected results:
"**Glod, Alba (Almașu Mare)**" is shown in the  search bar

Actual result:

The locality  ""_Glob_, Alba (Almașu Mare"") isn't displayed in the search bar

In the  search bar are displayed another localities 

**The correct name of the locality is ""Glod, Alba (Almaşu Mare)""**



![Image](https://github.com/peviitor-ro/ui.orase/assets/127322865/a2092710-6a17-46fc-b5d8-d53ed4628072)

![Image](https://github.com/peviitor-ro/ui.orase/assets/127322865/e538a858-0a77-4ccf-aa7e-d99d4bf25dfb)

![Image](https://github.com/peviitor-ro/ui.orase/assets/127322865/38bcfd4f-9128-4deb-891d-0610b615b1e6)

**Comment by AdelinaGuliman** [comment]
Fixed

**Comment by AdelinaGuliman** [comment]
@AdinaIT please retest

**Comment by AdinaIT** [comment]
**Retesting**

- Run TC

- The bug is no longer reproducible with the initial steps.

- Data is now correct after fixing the bug.

- Validating the bug fix
