### ISSUE TITLE
Sântămăria De Piatră, Hunedoara (Călan) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#40]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Sântămăria de Piatră" in the search bar
3. Select Sântămăria De Piatră, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar - Sântămăria De Piatră, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![19](https://github.com/peviitor-ro/ui.orase/assets/143128512/3e6929ff-28d1-45fa-a508-fb5b9b1a5bd0)
![20](https://github.com/peviitor-ro/ui.orase/assets/143128512/d5526d4f-10cd-40b0-80a7-9e4b67d01418)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
