### ISSUE TITLE
"Pocola, Feneriș, Petrani, Poietari, Sânmartin de Beiuș" are villages in "Pocola" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4060]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Comment by chiparca81** [comment]
**Precondition**

The website is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Pocola"

**Expected result**

In the drop down menu you find "Pocola, BIHOR(Pocola)"

**Test Data**

Pocola

**Comment by chiparca81** [comment]
**Steps 2**

Write "Feneriș"

**Expected result**

In the drop down menu you find "Feneriș, BIHOR(Pocola)"

**Test Data**

Feneriș

**Comment by chiparca81** [comment]
**Steps 3**

Write "Petrani"

**Expected result**

In the drop down menu you find "Petrani, BIHOR(Pocola)"

**Test Data**

Petrani

**Comment by chiparca81** [comment]
**Steps 4**

Write "Poietari"

**Expected result**

In the drop down menu you find "Poietari, BIHOR(Pocola)"

**Test Data**

Poietari

**Comment by chiparca81** [comment]
**Steps 5**

Write "Sânmartin de Beiuș"

**Expected result**

In the drop down menu you find "Sânmartin de Beiuș, BIHOR(Pocola)"

**Test Data**

Sânmartin de Beiuș

**Comment by TaniaR33** [comment]
Aici la fel ai uitat sa pui la Precondition site ul catre motorul de cautare
