### ISSUE TITLE
Sântămăria De Piatră, Hunedoara (Călan) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#41]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Sântămăria de Piatră" in the search bar
3. Select Sântămăria De Piatră, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![21](https://github.com/peviitor-ro/ui.orase/assets/143128512/3e2aa53b-690e-436b-90be-71288eb4172f)
![22](https://github.com/peviitor-ro/ui.orase/assets/143128512/1f78ab3c-2610-47fe-a417-0eccb13c11ee)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
