### ISSUE TITLE
”Sarmizegetusa”, ”Breazova”, ”Hobița-Grădiște”, ”Păucinești”, ”Zeicani” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#4104]
Description: 
When user writes ”Sarmizegetusa”, ”Breazova”, ”Hobița-Grădiște”, ”Păucinești”, ”Zeicani” the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Breazova"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Breazova, HUNEDOARA (Sarmizegetusa)".

**Comment by bogi1492** [comment]
> **Step 7**
Write in the search bar "Păucinești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Păucinești, HUNEDOARA (Sarmizegetusa)".

**Comment by bogi1492** [comment]
> **Step 8**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 9**
Write in the search bar "Păucinești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Păucinești, HUNEDOARA (Sarmizegetusa)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4104
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC[”Sarmizegetusa”, ”Breazova”, ”Hobița-Grădiște”, ”Păucinești”, ”Zeicani” are listed in the drop-down menu](https://github.com/peviitor-ro/ui.orase/issues/4104)
#4104

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Zeicani, HUNEDOARA (Sarmizegetusa)"

Actual result (displayed):
In STEP9 is displayed :
In the drop down menu you find "Sat Păucinești, HUNEDOARA (Sarmizegetusa)" same like in STEP 7

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/af252e70-7f8e-4e33-8710-3e1cf33c7efc)

**Comment by bogi1492** [comment]
Modificat, poti retesta.
