### ISSUE TITLE
Valea Sângeorgiului, Hunedoara (Călan) - The full name is not visible in the search bar

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#42]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Valea Sângeorgiului" in the search bar
3. Select Valea Sângeorgiului, Hunedoara (Călan) from the list

EXPECTED RESULTS:
The full name is visible in the search bar -Valea Sângeorgiului, Hunedoara (Călan)

ACTUAL RESULTS:
The full name is not visible in the search bar.

![23](https://github.com/peviitor-ro/ui.orase/assets/143128512/0589c11a-badc-49ec-be8c-8390eda2c964)
![24](https://github.com/peviitor-ro/ui.orase/assets/143128512/6c44119d-8596-4b07-ac23-62122b511f9a)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta.
