### ISSUE TITLE
"Logrești" is listed in the drop-down menu

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/ui.orase#4207]
**Description:** 
"Logrești" is listed in the drop-down menu alongside its corresponding county, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by iBixee** [comment]
>**Step 1**
Type "Logrești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Logrești, GORJ".

**Comment by ElenaColonel** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Open URL in browser.
Type "Logrești" in the search bar.

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Comuna Logrești, GORJ".

ACTUAL RESULTS:
"Comuna Logrești, GORJ" is missing in the drop-down menu.



![Image](https://github.com/peviitor-ro/ui.orase/assets/150712598/f3bb8061-5e32-4827-b1ce-88950e16e847)

**Comment by ElenaColonel** [comment]
![Image](https://github.com/peviitor-ro/ui.orase/assets/150712598/8c9779d2-33bf-43fa-a5a2-a6907ec6cdf5)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi

**Comment by AdelinaGuliman** [comment]
@ElenaColonel please retest

**Comment by AdelinaGuliman** [comment]
@ElenaColonel please remove the bug and FAIL labels and put the label PASS if the TC is PASS
