### ISSUE TITLE
"Mirăslău", "Cicău", "Decea", "Lopadea Veche", "Ormeniș", "Rachiș" are villages in "Mirăslău" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#433]
Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing.

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Mirăslău"

**Expected result**: In the drop down menu you find "Mirăslău, ALBA( Mirăslău)"

**Comment by DeedeeDL** [comment]
>>Steps 2 : Press and hold the Back key to delete the text.

**Expected result**: The search bar is empty and the cursor active

**Comment by DeedeeDL** [comment]
>> **Steps 3**:  Click on the search bar and write "Cicău"

**Expected result**: In the drop down menu you find "Cicău, ALBA( Mihalț)"

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Decea"

**Expected result**: In the drop down menu you find "Decea, ALBA( Mihalț)"

**Comment by DeedeeDL** [comment]
>>Steps 6: Press and hold the Back key to delete the text.

**Expected result**: The search bar is empty and the cursor active

**Comment by DeedeeDL** [comment]
>> **Steps 7**:  Click on the search bar and write "Lopadea Veche"

**Expected result**: In the drop down menu you find "Lopadea Veche, ALBA( Mihalț)"

**Comment by DeedeeDL** [comment]
>> **Steps 9**:  Click on the search bar and write"Ormeniș"

**Expected result**: In the drop down menu you find ""Ormeniș, ALBA( Mihalț)"

**Comment by DeedeeDL** [comment]
>>Steps 10 : Press and hold the Back key to delete the text.

**Expected result**: The search bar is empty and the cursor active

**Comment by DeedeeDL** [comment]
>> **Steps 11**:  Click on the search bar and write "Rachiș"

**Expected result**: In the drop down menu you find "Rachiș, ALBA( Mihalț)"

**Comment by CristinaVoicu** [comment]
Environment: Run Tests
Browser: Google Chrome
Version: 122.0.6261.112
Device: Laptop
OS: Windows 10 Pro 22H2

Steps to reproduce:

1 Open the https://peviitor-ro.github.io/ui.orase/
2. Type in the search bar "Mirăslău"
3. Type in the search bar "Cicău''
4. Type in the search bar "Decea''
5. Type in the search bar ''Lopadea Veche''
6. Type in the search bar ''Ormeniș''

Expected results:

In the drop down menu you find "Mirăslău, ALBA( Mirăslău)"
In the drop down menu you find "Cicău, ALBA( Mihalț)"
In the drop down menu you find "Decea, ALBA( Mihalț)"
In the drop down menu you find "Lopadea Veche, ALBA( Mihalț)"
In the drop down menu you find ""Ormeniș, ALBA( Mihalț)"




Actual results:

In the drop down menu you find "Mirăslău, ALBA( Alba)"
In the drop down menu you find "Cicău, ALBA(Mirăslău)"
In the drop down menu you find "Decea, ALBA(Mirăslău)"
In the drop down menu you find "Lopadea Veche, ALBA(Mirăslău)"
In the drop down menu you find "Ormeniș, ALBA(Mirăslău)"



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/e0d12b35-ce5d-4b2c-beeb-4f3bc6f67ef3)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/9c8300c9-0135-4ddc-905e-d3e565a6620c)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/3fdc8e53-8cdf-4427-a0d8-89dc4cb1e6aa)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/c5c1a397-fe5a-4193-9bcc-fd943d320cc1)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/d91ba4ea-e8b0-465c-b311-bc890c942345)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/c524793d-446b-4798-b70a-1163fa4ec67a)

**Comment by DeedeeDL** [comment]
Corrected. please retest

**Comment by CristinaVoicu** [comment]
ok

**Comment by AdelinaGuliman** [comment]
@CristinaVoicu when you test the locations pls use this tool [Orase.ui](https://peviitor-ro.github.io/ui.orase/)
