### ISSUE TITLE
"Gura Șuții" is listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#4336]
Description:
"Gura Șuții" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Elena1303996** [comment]
@AdelinaGuliman, please add the steps.

**Comment by AdelinaGuliman** [comment]
@Elena1303996 you can retest
