### ISSUE TITLE
"Mămăligani", "Negrești","Oncești ", "Poienile-Mogoș","Tomești", " Valea Barnii", "Valea Bârluțești", "Valea Cocești"," Valea Giogești", "Valea Mlacii",  "Valea Țupilor"  are villages in "Mogoș" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#435]
Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing.

**Comment by CristinaVoicu** [comment]
There are no steps to run the test cases for each location in the title.

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Mămăligani"

**Expected result**: In the drop down menu you find "Mămăligani, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 3**:  Click on the search bar and write "Oncești"

**Expected result**: In the drop down menu you find "Oncești, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 4**:  Click on the search bar and write "Poienile-Mogoș"

**Expected result**: In the drop down menu you find "Poienile-Mogoș, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Tomești"

**Expected result**: In the drop down menu you find "Tomești, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 6**:  Click on the search bar and write "Valea Barnii""

**Expected result**: In the drop down menu you find "Valea Barnii", Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 7**:  Click on the search bar and write "Valea Bârluțești""

**Expected result**: In the drop down menu you find "Valea Bârluțești, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 8**:  Click on the search bar and write "Valea Cocești"

**Expected result**: In the drop down menu you find "Valea Cocești, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 9**:  Click on the search bar and write "Valea Giogești"

**Expected result**: In the drop down menu you find "Valea Giogești, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 10**:  Click on the search bar and write "Valea Mlacii"

**Expected result**: In the drop down menu you find "Valea Mlacii, Alba( Mogoș)"

**Comment by DeedeeDL** [comment]
>> **Steps 11**:  Click on the search bar and write "Valea Țupilor"

**Expected result**: In the drop down menu you find "Valea Țupilor, Alba( Mogoș)"
