### ISSUE TITLE
”Cernele”, ”Cernele de Sus”, ”Izvorul Rece” are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#4364]
**Description**: 
When user writes Cernele”, ”Cernele de Sus”, ”Izvorul Rece” the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

**Precondition**:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Catalinay** [comment]
> **Step 1**
Write in the search bar "Cernele"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Cernele, DOLJ(CRAIOVA)".

**Comment by Catalinay** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Catalinay** [comment]
> **Step 3**
Write in the search bar "Cernele de Sus"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Cernele de Sus, DOLJ(CRAIOVA)".

**Comment by Catalinay** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by Catalinay** [comment]
> **Step 5**
Write in the search bar "Izvorul Rece"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Izvorul Rece, DOLJ(CRAIOVA)".

**Comment by Georgianaredenstein** [comment]
Catalinay  When user writes ”Cernele de Sus”, ”Izvorul Rece” the locations do not appear in the drop-down menu from search bar !

**Comment by OvidiuAl3x** [comment]
Este deschis Issues pe [backend ](https://github.com/peviitor-ro/orase/issues/186)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
