### ISSUE TITLE
”Rovine” is listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#4365]
Description: 
When user writes ”Rovine” the location appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
Environment: Run Tests
Browser: Chrome 123
OS: Windows 10 
 
Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : ”Rovine” is listed in the drop-down menu
[#4365](https://github.com/peviitor-ro/ui.orase/issues/4365)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Rovine, DOLJ(CRAIOVA)"


Actual result (displayed):
Missing Precondition:
The [website] it isn't up and running, missing link!
The link to the law isn't displayed

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/1ec66363-cec7-4e6c-ae81-aa1f3590b887)

**Comment by Catalinay** [comment]
According to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189) , the location should appear in the drop-down menu as "Sat Rovine, DOLJ(CRAIOVA)". when the user writes "Rovine" in the search-bar. 

![Image](https://github.com/peviitor-ro/ui.orase/assets/161432647/18fbd52b-3c8f-414b-b84f-201637506251)

**Comment by OvidiuAl3x** [comment]
Este deschis Issues pe [backend ](https://github.com/peviitor-ro/orase/issues/184)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
