### ISSUE TITLE
"Ocoliș", "Lunca Largă", "Runc", "Vidolm",are villages in "Ocoliș" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#437]
Description : When user is typing "Ocoliș"/"Lunca Largă"/"Runc"/"Vidolm"in the search bar, the locations should appear in the dropdown menu correctly spelled and with localities information [(as in Law nr. 2 din 16 februarie 1968)](https://legislatie.just.ro/Public/DetaliiDocument/189)
Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Ocoliș"

**Expected result**: In the drop down menu you find "Ocoliș, ALBA( Ocoliș)"

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Lunca Largă"

**Expected result**: In the drop down menu you find "Lunca Largă, ALBA( Ocoliș)"

**Comment by DeedeeDL** [comment]
>>Steps 4: Press and hold the Back key to delete the text.

**Expected result**: The search bar is empty and the cursor active

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Runc"

**Expected result**: In the drop down menu you find "Runc, ALBA( Ocoliș)"

**Comment by DeedeeDL** [comment]
>>Steps 6: Press and hold the Back key to delete the text.

**Expected result**: The search bar is empty and the cursor active

**Comment by DeedeeDL** [comment]
>> **Steps 7*:  Click on the search bar and write "Vidolm"

**Expected result**: In the drop down menu you find "Vidolm, ALBA( Ocoliș)"

**Comment by CristinaVoicu** [comment]
Environment: Run Tests
Browser: Google Chrome
Version: 122.0.6261.112
Device: Laptop
OS: Windows 10 Pro 22H2

Steps to reproduce:

1 Open the https://peviitor-ro.github.io/ui.orase/
2. Type in the search bar ''Ocoliș"


Expected results:
In the drop down menu you find "Ocoliș, ALBA, (Ocoliș)"


Actual results:
In the drop down menu you find "Ocoliș, ALBA, (Alba)"



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/63398410-a89d-4ea4-a6b6-43e64ec04f34)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi, pe [ui.orase](https://peviitor-ro.github.io/ui.orase/)

**Comment by CristinaVoicu** [comment]
ok
