### ISSUE TITLE
" Bacău de Mijloc, Bulci, Țela" are villages in "Bata" common, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#441]

**Comment by chiparca81** [comment]
**Precondition**

Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by chiparca81** [comment]
**Steps  2**

Write "Bacău de Mijloc"

**Expected result**

In the drop down menu you find "Bacău de Mijloc, ARAD()"

**Test Data**

Bacău de Mijloc

**Comment by chiparca81** [comment]
**Steps 2**

Write ""

**Expected result**

In the drop down menu you find ", ARAD()"

**Test Data**

**Comment by chiparca81** [comment]
**Steps 3**

Write "Țela"

**Expected result**

In the drop down menu you find "Țela, ARAD(Bata)"

**Test Data**

Țela

**Comment by Florin201092** [comment]
@chiparca81 
Take a look on the TC format, there are missing a lot of elements and some data for testing.
I marked that with two eyes.
