### ISSUE TITLE
Silvașu De Jos/Silvașu De Sus, Hunedoara (Hațeg) - Are not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#45]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Silvașu De Jos" in the search bar (/Silvașu De Sus)
3. Select Silvașu De Jos, Hunedoara (Hațeg) from the list (/Silvașu De Sus, Hunedoara (Hațeg))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![27](https://github.com/peviitor-ro/ui.orase/assets/143128512/21c2825e-dc89-477d-a536-3dc75acecaa9)
![28](https://github.com/peviitor-ro/ui.orase/assets/143128512/f587ac02-1c46-496a-8ec4-a673ca66b0e8)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
