### ISSUE TITLE
“Râmeț", "Boțani", " Brădești", "Cheia", "Cotorăști", "Florești", "Olteni", "Valea Făgetului", "Valea Inzelului", "Valea Mănăstirii", "Valea Poienii", "Valea Uzei", "Vlădești" are villages in "Râmeț" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#453]
**Description :** When user is typing the villages in the search bar, the locations should appear in the dropdown menu correctly spelled and with localities information [(as in Law nr. 2 din 16 februarie 1968)](https://legislatie.just.ro/Public/DetaliiDocument/189)
**Preconditions :** the website (https://peviitor-ro.github.io/ui.orase/)  is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Râmeț"

**Expected result**: In the drop down menu you find "Râmeț, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 2**:  Click on the search bar and write "Boțani"

**Expected result**: In the drop down menu you find "Boțani, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 3**:  Click on the search bar and write "Brădești"

**Expected result**: In the drop down menu you find "Brădești, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 4**:  Click on the search bar and write "Cheia"

**Expected result**: In the drop down menu you find "Cheia, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Cotorăști"

**Expected result**: In the drop down menu you find "Cotorăști, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 7**:  Click on the search bar and write "Olteni"

**Expected result**: In the drop down menu you find "Olteni, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 8**:  Click on the search bar and write "Valea Făgetului"

**Expected result**: In the drop down menu you find "Valea Făgetului, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 9**:  Click on the search bar and write "Valea Inzelului"

**Expected result**: In the drop down menu you find "Valea Inzelului, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 10**:  Click on the search bar and write "Valea Mănăstirii"

**Expected result**: In the drop down menu you find "Valea Mănăstirii, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 12**:  Click on the search bar and write "Valea Uzei"

**Expected result**: In the drop down menu you find "Valea Uzei ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
>> **Steps 13**:  Click on the search bar and write "Vlădeștiare"

**Expected result**: In the drop down menu you find "Vlădeștiare, ALBA( Râmeț)"

**Comment by DeedeeDL** [comment]
> > > **Steps 13**:  Click on the search bar and write "Vlădești"
> 
> **Expected result**: In the drop down menu you find "Vlădești, ALBA( Râmeț)"

Corrected. You can retest now

**Comment by CristinaVoicu** [comment]
ok
