### ISSUE TITLE
"Țaga", "Năsal", "Sântejude", "Sântejude-Vale" and "Sântioana" villages are listed in the drop-down menu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#4565]
The villages are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by TaniaR33** [comment]
Buna, nu ai adaugat Expected si Actual(Pasii)

**Comment by DeedeeDL** [comment]
> **Step 1**
Write in the search bar "Țaga"

**Expected results** 
The location appears in the drop-down menu as "Sat Țaga, CLUJ (Țaga)"

**Comment by DeedeeDL** [comment]
> **Step 2**
Write in the search bar "Năsal"

**Expected results** 
The location appears in the drop-down menu as "Sat Năsal, CLUJ (Țaga)"

**Comment by DeedeeDL** [comment]
> **Step 3**
Write in the search bar "Sântejude"

**Expected results** 
The location appears in the drop-down menu as "Sat Sântejude, CLUJ (Țaga)"

**Comment by DeedeeDL** [comment]
> **Step 4**
Write in the search bar "Sântejude-Vale"

**Expected results** 
The location appears in the drop-down menu as "Sat Sântejude-Vale, CLUJ (Țaga)"

**Comment by DeedeeDL** [comment]
> **Step 5**
Write in the search bar "Sântioana"

**Expected results** 
The location appears in the drop-down menu as "Sat Sântioana, CLUJ (Țaga)"

**Comment by DeedeeDL** [comment]
Tania, retest please
