### ISSUE TITLE
"Rieni, Cucuceni, Ghighișeni, Petrileni, Sudrigiu, Valea de Jos" are villages in "Rieni" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4585]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Rieni"

**Expected result**

In the drop down menu you find "**Sat** , **BIHOR**(Rieni)"

**Test Data**

Rieni

**Comment by chiparca81** [comment]
**Steps 2**

Write "Cucuceni"

**Expected result**

In the drop down menu you find "**Sat** Cucuceni, **BIHOR**(Rieni)"

**Test Data**

Cucuceni

**Comment by chiparca81** [comment]
**Steps 3**

Write "Ghighișeni"

**Expected result**

In the drop down menu you find "**Sat** Ghighișeni, **BIHOR**(Rieni)"

**Test Data**

Ghighișeni

**Comment by chiparca81** [comment]
**Steps 4**

Write "Petrileni"

**Expected result**

In the drop down menu you find "**Sat** Petrileni, **BIHOR**(Rieni)"

**Test Data**

Petrileni

**Comment by chiparca81** [comment]
**Steps 5**

Write "Sudrigiu"

**Expected result**

In the drop down menu you find "**Sat** Sudrigiu, **BIHOR**(Rieni)"

**Test Data**

Sudrigiu

**Comment by chiparca81** [comment]
**Steps 6**

Write "Valea de Jos"

**Expected result**

In the drop down menu you find "**Sat** Valea de Jos, **BIHOR**(Rieni)"

**Test Data**

Valea de Jos

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4209
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC "Rieni, Cucuceni, Ghighișeni, Petrileni, Sudrigiu, Valea de Jos" are villages in "Rieni" commune, "BIHOR" county
[#4585](https://github.com/peviitor-ro/ui.orase/issues/4585)

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Rieni, BIHOR (Rieni)"


Actual result (displayed):
In STEP1 is displayed : n the drop down menu you find "Sat , BIHOR(Rieni)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/e04b575c-697b-4368-9548-1f32c20fcb86)
