### ISSUE TITLE
“Săsciori", "Căpâlna", " Dumbrava", “Laz", "Loman", " Pleși", "Răchita", "Sebeșel","Tonea" are villages in "Săsciori" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#465]
**Description :** When user is typing the villages in the search bar, the locations should appear in the dropdown menu correctly spelled and with localities information [(as in Law nr. 2 din 16 februarie 1968)](https://legislatie.just.ro/Public/DetaliiDocument/189)
**Preconditions :** the website (https://peviitor-ro.github.io/ui.orase/)  is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>> **Steps 2**:  Click on the search bar and write "Căpâlna"

**Expected result**: In the drop down menu you find "Căpâlna, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 3**:  Click on the search bar and write "Dumbrava"

**Expected result**: In the drop down menu you find "Dumbrava, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 4**:  Click on the search bar and write "Laz"

**Expected result**: In the drop down menu you find "Laz, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 4**:  Click on the search bar and write "Loman"

**Expected result**: In the drop down menu you find "Loman, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Pleși"

**Expected result**: In the drop down menu you find "Pleși, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 7**:  Click on the search bar and write "Sebeșel"

**Expected result**: In the drop down menu you find "Sebeșel, ALBA(Săsciori)"

**Comment by DeedeeDL** [comment]
>> **Steps 8**:  Click on the search bar and write "Tonea"

**Expected result**: In the drop down menu you find "Tonea, ALBA(Săsciori)"

**Comment by AndraADM** [comment]
enviroment: test
browser: opera
device: laptop
OS: Windows 10

Steps to reproduce:
1. Open the [website](https://peviitor-ro.github.io/ui.orase/)
2. Type in the search bar "Săsciori"

Expected results:
1."Săsciori" is shown in search bar

Actual results:
1.In the drop-down menu is displayed "Săsciori, Alba" but (Săsciori) is missing




![Image](https://github.com/peviitor-ro/ui.orase/assets/142739627/7db2d9e8-3931-43ce-a1cd-3f130690461f)

**Comment by DeedeeDL** [comment]
> > > **Steps 1**:  Click on the search bar and write "Săsciori".
> 
> **Expected result**: In the drop down menu you find "Săsciori, ALBA(Săsciori)"

Corrected. Please retest
