### ISSUE TITLE
Valea De Brazi, Hunedoara (Uricani) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#47]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Valea de Brazi" in the search bar
3. Select Valea De Brazi, Hunedoara (Uricani) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![31](https://github.com/peviitor-ro/ui.orase/assets/143128512/c7ca64ee-9d45-481e-9cb9-6efc23daece0)
![32](https://github.com/peviitor-ro/ui.orase/assets/143128512/b1abc7af-91b2-472f-a5f8-1efc15626ad4)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
