### ISSUE TITLE
 Baia De Criș, Hunedoara - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#48]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Baia de Criș" in the search bar
3. Select Baia De Criș, Hunedoara from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![33](https://github.com/peviitor-ro/ui.orase/assets/143128512/d10e3c5f-44d5-4e6a-986b-ad3da5286103)
![34](https://github.com/peviitor-ro/ui.orase/assets/143128512/a87dbf87-54f3-48ab-8ed2-b6d474fb63ef)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
