### ISSUE TITLE
"Roșia, Lazuri" are villages in "Roșia" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#4965]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Roșia"

**Expected result**

In the drop down menu you find "**Sat** Roșia, **BIHOR**(Roșia)"

**Test Data**

Roșia

**Comment by chiparca81** [comment]
**Steps 2**

Write "Lazuri"

**Expected result**

In the drop down menu you find "**Sat** Lazuri, **BIHOR**(Roșia)"

**Test Data**

Lazuri

**Comment by yonutzu** [comment]
Environment: Run Tests - 4965
Browser: Chrome 124
OS: Windows 11

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC "Roșia, Lazuri" are villages in "Roșia" commune, "BIHOR" county](https://github.com/peviitor-ro/ui.orase/issues/4965) to
3. Press "X" to pass to the next step


Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Roșia, BIHOR(Roșia)"
Press "X" to pass to the next step

Actual result (displayed):
In STEP 2 is displayed : Sat Lazuri, BIHOR(Roșia)
Expected result
To pass step 2, press "x" in the drop-down menu

![Image](https://github.com/peviitor-ro/ui.orase/assets/76839121/f6729c16-33cd-4d43-a4ea-4585bcbd750e)

**Comment by yonutzu** [comment]
everythink is ok
