### ISSUE TITLE
Almașu Mic De Munte, Hunedoara (Balșa) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#50]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Almașu Mic de Munte" in the search bar
3. Select Almașu Mic De Munte, Hunedoara (Balșa) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![35](https://github.com/peviitor-ro/ui.orase/assets/143128512/6d5c94af-c603-4946-a1c5-e6dbff2fd4fe)
![36](https://github.com/peviitor-ro/ui.orase/assets/143128512/f4136a7a-c08b-4b54-8d5d-ef4687ec74ab)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
