### ISSUE TITLE
"Tarcea, Adoni, Galoșpetreu" are villages in "Tarcea" commune, "BIHOR" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#5002]
**Description**

When an user search a location, this appear in the drop-down menu
according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition**

The website ( https://peviitor-ro.github.io/ui.orase/ ) is up an running.
Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Write "Tarcea"

**Expected result**

In the drop down menu you find "**Sat** Tarcea, **BIHOR**(Tarcea)
**Comuna** Tarcea, **BIHOR**"

**Test Data**

Tarcea

**Comment by chiparca81** [comment]
**Steps 2**

Write "Adoni"

**Expected result**

In the drop down menu you find "**Sat** Adoni, **BIHOR**(Tarcea)"

**Test Data**

Adoni

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4209
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC : "Tarcea, Adoni, Galoșpetreu" are villages in "Tarcea" commune, "BIHOR" county](https://github.com/peviitor-ro/ui.orase/issues/5002)
#5002

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :
"Sat Tarcea, BIHOR (Tarcea)"
"Sat Adoni, BIHOR (Tarcea)"
"Sat Galoșpetreu, BIHOR (Tarcea)"

Actual results:
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/0e88c2a0-dfde-46c6-8c44-22ff46b77ab4)

STEP3 - "Sat Galoșpetreu, BIHOR (Tarcea)" is missing

**Comment by chiparca81** [comment]
**Steps 3**

Write "Galoșpetreu"

**Expected result**

In the drop down menu you find "**Sat** Galoșpetreu, **BIHOR**(Tarcea)"

**Test Data**

Galoșpetreu
