### ISSUE TITLE
Căinelu De Sus, Hunedoara (Băița) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#51]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Căinelu De Sus" in the search bar
3. Select Căinelu De Sus, Hunedoara (Băița) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![37](https://github.com/peviitor-ro/ui.orase/assets/143128512/6f16b433-7dfc-4a34-b2c5-8f91fe611ce2)
![38](https://github.com/peviitor-ro/ui.orase/assets/143128512/0c725798-c929-47b6-b4f3-00bbc5f56642)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
