### ISSUE TITLE
Orăștioara De Jos, Hunedoara (Beriu) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#52]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Orăștioara De Jos" in the search bar
3. Select Orăștioara De Jos, Hunedoara (Beriu) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![39](https://github.com/peviitor-ro/ui.orase/assets/143128512/c8349c43-0c8a-4c2f-8d93-fb970c681a6b)
![40](https://github.com/peviitor-ro/ui.orase/assets/143128512/9ea54a52-3ad4-4ebd-8ffa-76e8898611e5)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
