### ISSUE TITLE
“Scărișoara", "Bârlești", " Botești", “Fața-Lăzești", "Florești", " Lăzești", "Lespezea", "Maței","Negești", "Prelucă", "Runc", "Sfoartea", "Știuleți", "Trâncești"  are villages in "Scărișoara" common, "ALBA" county

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#530]
**Description :** When user is typing the villages in the search bar, the locations should appear in the dropdown menu correctly spelled and with localities information (as in Law nr. 2 din 16 februarie 1968)](https://legislatie.just.ro/Public/DetaliiDocument/189)
**Preconditions :** the website (https://peviitor-ro.github.io/ui.orase/)  is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>> **Steps 1**:  Click on the search bar and write "Scărișoara".

**Expected result**: In the drop down menu you find "Scărișoara, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 2**:  Click on the search bar and write "Bârlești".

**Expected result**: In the drop down menu you find "Bârlești, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 3**:  Click on the search bar and write "Botești".

**Expected result**: In the drop down menu you find "Botești, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 4**:  Click on the search bar and write "Fața-Lăzești".

**Expected result**: In the drop down menu you find "Fața-Lăzești, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 5**:  Click on the search bar and write "Florești".

**Expected result**: In the drop down menu you find "Florești, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 6**:  Click on the search bar and write "Lăzești".

**Expected result**: In the drop down menu you find "Lăzești, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 7**:  Click on the search bar and write "Lespezea".

**Expected result**: In the drop down menu you find "Lespezea, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 8**:  Click on the search bar and write "Maței".

**Expected result**: In the drop down menu you find "Maței, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 10**:  Click on the search bar and write "Prelucă".

**Expected result**: In the drop down menu you find "Prelucă, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 11**:  Click on the search bar and write "Runc".

**Expected result**: In the drop down menu you find "Runc, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 12**:  Click on the search bar and write "Sfoartea".

**Expected result**: In the drop down menu you find "Sfoartea, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 13**:  Click on the search bar and write "Știuleți".

**Expected result**: In the drop down menu you find "Știuleți, ALBA(Scărișoara)"

**Comment by DeedeeDL** [comment]
>> **Steps 14**:  Click on the search bar and write "Trâncești".

**Expected result**: In the drop down menu you find "Trâncești, ALBA(Scărișoara)"

**Comment by bogi1492** [comment]
browser: Google Chrome
device: Laptop
OS: Windows 11

Steps to reproduce:

Open the [website](https://peviitor-ro.github.io/ui.orase/)
Type in the search bar "Șeușa"

Expected results:
"Șeușa" is shown in search bar

Actual result:
1."Șeușa" is not inserted. In search bar does not work added the letter Ș
2.The following message is returned: "Sunt permise doar litere"
