### ISSUE TITLE
Sat Secu, NEAMȚ (BICAZ) is missing

### ISSUE THREAD

**Issue by SabIoana** [peviitor-ro/ui.orase#5397]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:
1. Open URL in the browser
2. Type "Secu" in the search bar

EXPECTED RESULTS:
The location is listed in the drop-down menu as "Sat Secu, NEAMȚ (BICAZ)"

ACTUAL RESULTS:
Secu from NEAMT(BICAZ) is missing

![Screenshot 2024-05-10 174733](https://github.com/peviitor-ro/ui.orase/assets/135150327/eb176d12-7086-4ac6-8b47-2f3d78bf1588)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestetzi

**Comment by AdelinaGuliman** [comment]
@SabIoana please retest!
