### ISSUE TITLE
Steierdorf - Caras-Severin - space between coma and  the name of the village

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#54]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: PC
OS: Windows 10

STEPS TO REPRODUCE:

Open URL in browser
Type "Steierdorf" in the search bar
Looking after "Steierdorf - Caras-Severin".
Verify if it is spelled correctly.

**EXPECTED RESULTS:**
Village found and everything is spelled correctly.

**ACTUAL RESULTS:**
There is a space between the name of the village and coma. 

<img width="410" alt="Steierdorf, Caras-Severin - space between coma" src="https://github.com/peviitor-ro/ui.orase/assets/129604131/f131a7d6-7e94-4250-b9c4-cbd735ef546b">

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by DeedeeDL** [comment]
Retested. Pass
