### ISSUE TITLE
Bulzeștii De Sus/Bulzeștii De Jos, Hunedoara - Are not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#55]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

Open URL in browser
1. Type "Bulzeștii De Sus" in the search bar (/Bulzeștii De Jos)
2. Select Bulzeștii De Sus, Hunedoara from the list (/Bulzeștii De Jos, Hunedoara (Bulzeștii De Sus))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![41](https://github.com/peviitor-ro/ui.orase/assets/143128512/88298af0-1910-477b-8566-9b25e0fad6ee)
![42](https://github.com/peviitor-ro/ui.orase/assets/143128512/7b024af1-59ad-4548-bde3-5975a478b7ad)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by danielastanculesc** [comment]
Mai trebuie modificat si la localitatea de care apartine, adica ce este in paranteza.
![60](https://github.com/peviitor-ro/ui.orase/assets/143128512/88e0758e-0602-4486-bb0f-daba0c1b1eb7)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
