### ISSUE TITLE
”Odoreu”, ”Berindan”, ”Cucu” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#5564]
Description: 
When user writes ”Odoreu”, ”Berindan”, ”Cucu” the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "Odoreu"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Odoreu, **SATU MARE** (Odoreu)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Berindan"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Berindan, **SATU MARE** (Odoreu)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Cucu"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Cucu, **SATU MARE** (Odoreu)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 5564
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: ”Odoreu”, ”Berindan”, ”Cucu” are listed in the drop-down menu
[#5564](https://github.com/peviitor-ro/ui.orase/issues/5564)

**Expected results:**
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :"Sat Odoreu, SATU MARE (Odoreu)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/ec7d8bb7-d200-48f4-972d-c672d1397f17)

in law wxist:
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/dac17da1-8337-414f-9a8a-da8000229f96)


**Actual results:**
In page "https://peviitor-ro.github.io/ui.orase/" not valid "Sat Odoreu, SATU MARE (Odoreu)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/f661e52e-ce1f-46d5-a470-be4bc14971a8)
