### ISSUE TITLE
Merișoru De Munte, Hunedoara (Cerbăl) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#56]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Merișoru De Munte" in the search bar
3. Select Merișoru De Munte, Hunedoara (Cerbăl) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![43](https://github.com/peviitor-ro/ui.orase/assets/143128512/7745d3c5-9be4-4eb1-ab65-b3473eefb110)
![44](https://github.com/peviitor-ro/ui.orase/assets/143128512/71131337-14bf-493d-b2ba-86576996f48d)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
