### ISSUE TITLE
"Șeușa" is listed in the drop-down menu

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/ui.orase#561]
**Description:** 
"Șeușa" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by iBixee** [comment]
>**Step 1**
Type "Șeușa" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Șeușa, Alba (Ciugud)".

**Comment by bogi1492** [comment]
![Image](https://github.com/peviitor-ro/ui.orase/assets/142155043/86fd0308-cacd-448d-b335-f2d7f28f953b)
