### ISSUE TITLE
”SĂLIȘTE”, ”Aciliu”, ”Amnaș”, ”Crinț”, ”Fântânele” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#5658]
Description: 
When user writes ”SĂLIȘTE”, ”Aciliu”, ”Amnaș”, ”Crinț”, ”Fântânele” the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "SĂLIȘTE"

**Expected results** 
The location appears in the drop-down menu as "**Oraș** SĂLIȘTE, **SIBIU** (SĂLIȘTE)".

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Aciliu"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Aciliu, **SIBIU** (SĂLIȘTE)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 6**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 7**
Write in the search bar "Crinț"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Crinț, **SIBIU** (SĂLIȘTE)".

**Comment by bogi1492** [comment]
> **Step 8**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 9**
Write in the search bar "Fântânele"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Fântânele, **SIBIU** (SĂLIȘTE)".

**Comment by ElenaBlejan** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 10 PRO

STEPS TO REPRODUCE:
Check TC: ”SĂLIȘTE”, ”Aciliu”, ”Amnaș”, ”Crinț”, ”Fântânele” are listed in the drop-down menu #5658 / Step7
Open URL in browser.
Type "Crinț" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Crinț, SIBIU (SĂLIȘTE)".

ACTUAL RESULTS:
"Sat Crinț, SIBIU (SĂLIȘTE)"  is missing in the drop-down menu and the follow message is displayed:  "Locatia nu a fost gasita!"



![Image](https://github.com/peviitor-ro/ui.orase/assets/128214531/9cd6b57a-cd60-4364-b20e-23296a1a8a34)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi!
