### ISSUE TITLE
”TĂLMACIU”, ”Colonia Tălmaciu”, ”Tălmăcel” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#5672]
Description: 
When user writes ”TĂLMACIU”, ”Colonia Tălmaciu”, ”Tălmăcel” the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "TĂLMACIU"

**Expected results** 
The location appears in the drop-down menu as "**Oraș** TĂLMACIU, **SIBIU** (TĂLMACIU)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Colonia Tălmaciu"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Colonia Tălmaciu, **SIBIU** (TĂLMACIU)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Tălmăcel"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Tălmăcel, **SIBIU** (TĂLMACIU)".

**Comment by ElenaColonel** [comment]
ENVIRONMENT: ui.orase
BROWSER: Google Chrome
Device: Laptop
OS: Windows 10 Pro

STEPS TO REPRODUCE:
Open URL in browser.
Type "TĂLMACIU" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Oraș TĂLMACIU, SIBIU (TĂLMACIU)".

ACTUAL RESULTS:
The location appears in the drop-down menu as "Oraș TĂLMACIU, SIBIU (TĂLMACIU)" and as " Oraș TĂLMACIU, SIBIU"

**Comment by ElenaColonel** [comment]
![Image](https://github.com/peviitor-ro/ui.orase/assets/150712598/f499ddae-63fb-47af-b9da-e93ca374be11)



![Image](https://github.com/peviitor-ro/ui.orase/assets/150712598/ed9af462-5dfc-445f-957a-60c9e996a93f)
