### ISSUE TITLE
"Pietrari", "Aluniș" are listed in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#5835]
Description: 
When user writes ”Pietrari” and "Aluniș" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Write in the search bar "Pietrari"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Pietrari, **DÂMBOVIȚA** (Pietrari)".

**Comment by AdelinaGuliman** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by AdelinaGuliman** [comment]
> **Step 3**
Write in the search bar "Aluniș"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Aluniș, **DÂMBOVIȚA** (Petrești)".

**Comment by BiancaJianu** [comment]
Environment: Run Tests - 5835
Browser: Mozila Firefox
OS: Windows 7

Steps to reproduce:
1 Open the @Adelina Guliman Test case ui.orase
2. Check TC: ”Pietrari” is listed in the drop-down menu
3. Press "x" button
4. Check TC: ”Aluniș” is listed in the drop-down menu
#5835

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Aluniș, DÂMBOVIȚA (Petrești)"

![Image](https://github.com/peviitor-ro/ui.orase/assets/92756534/8213940d-9845-43f6-bc29-eb1a1e95133f)

In law and actual result (displayed)exist:

![Image](https://github.com/peviitor-ro/ui.orase/assets/92756534/e8ebe6fd-8dcd-41ab-904e-601eac308b9c)

In page "https://peviitor-ro.github.io/ui.orase/" not valid - "Sat Aluniș, DÂMBOVIȚA (Petrești)".

**Comment by AdelinaGuliman** [comment]
Fixed! You can retest!
