### ISSUE TITLE
"Șilea" is listed in the drop-down menu

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/ui.orase#585]
**Description:** 
"Șilea" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by iBixee** [comment]
>**Step 1**
Type "Șilea" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "Șilea, Alba (Fărău)".

**Comment by bogi1492** [comment]
![Image](https://github.com/peviitor-ro/ui.orase/assets/142155043/810a9cc7-9ffe-475a-a7a7-cf656d91c86e)
