### ISSUE TITLE
"Poienarii Burchii", "Cărbunari", "Ologeni", "Piorești", "Podu Văleni", "Poienarii-Rali", "Poienarii Vechi" and "Tătărăi" villages are listed in the drop-down menu.

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/ui.orase#5926]
Description
The villages are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by Elena1303996** [comment]
>**Step 1**
Write in the search bar "Poienarii Burchii".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Poienarii Burchii **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 2**
Write in the search bar "Cărbunarii".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Cărbunari **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 3**
Write in the search bar "Ologeni".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Ologeni **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 4**
Write in the search bar "Piorești".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Piorești **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 5**
Write in the search bar "Podu Văleni".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Podu Văleni **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 6**
Write in the search bar "Poienarii-Rali".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Poienarii-Rali **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 7**
Write in the search bar "Poienarii Vechi ".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Poienarii Vechi  **PRAHOVA** (Poienarii Burchii)".

**Comment by Elena1303996** [comment]
>**Step 8**
Write in the search bar "Tătărăi".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Tătărăi **PRAHOVA** (Poienarii Burchii)".

**Comment by yonutzu** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Google Chrome
Device: Laptop
OS: Windows 11 PRO

STEPS TO REPRODUCE:
Check TC: "Poienarii Burchii", "Cărbunari", "Ologeni", "Piorești", "Podu Văleni", "Poienarii-Rali", "Poienarii Vechi" and "Tătărăi" villages are listed in the drop-down menu.
[#5926](https://github.com/peviitor-ro/ui.orase/issues/5926) / Step2
Open URL in browser.
Type "Cărbunarii" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Cărbunari PRAHOVA (Poienarii Burchii)".

ACTUAL RESULTS:
"Cărbunarii" is missing in the drop-down menu and the follow message is displayed: "Locatia nu a fost gasita!"















![Image](https://github.com/peviitor-ro/ui.orase/assets/76839121/1dd1c2ce-da3c-42c8-bfb3-e127943506ef)

**Comment by Elena1303996** [comment]
@yonutzu  The bug is fixed. Thank !
