### ISSUE TITLE
”ISACCEA”, ”Revărsarea”, ”Tichilești” are listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#6094]
Description: 
When user writes ”ISACCEA”, ”Revărsarea”, ”Tichilești” the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by bogi1492** [comment]
> **Step 1**
Write in the search bar "ISACCEA"

**Expected results** 
The location appears in the drop-down menu as "**Oraș** ISACCEA, **TULCEA** (ISACCEA)".

**Comment by bogi1492** [comment]
> **Step 2**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 3**
Write in the search bar "Revărsarea"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Revărsarea, **TULCEA** (ISACCEA)".

**Comment by bogi1492** [comment]
> **Step 4**
Press "x" button.

**Expected results** 
The location was deleted from the search bar.

**Comment by bogi1492** [comment]
> **Step 5**
Write in the search bar "Tichilești"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Tichilești, **TULCEA** (ISACCEA)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 6094
Browser: Chrome 123
OS: Windows 10

**Steps to reproduce:**
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: [”ISACCEA”, ”Revărsarea”, ”Tichilești” are listed in the drop-down menu](https://github.com/peviitor-ro/ui.orase/issues/6094)
#6094

**Expected results:**
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :"Sat Tichilești, TULCEA (ISACCEA)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/f13a727c-c7c9-4e06-9e0d-efd4f2e0863a)


**Actual results:**
Is displayed: "**Oras** Tichilesti, **Tulce**a (ISSACEA)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/8c5b21da-d689-4327-81fe-d880e6e739df)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi!
