### ISSUE TITLE
Boiu De Jos/Boiu De Sus, Hunedoara (Gurasada) - Are not written correctly 

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#61]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2.  Type "Boiu De Jos" in the search bar (/Boiu De Sus)
3.  Select Boiu De Jos, Hunedoara (Gurasada) from the list (/Boiu De Sus, Hunedoara (Gurasada))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![47](https://github.com/peviitor-ro/ui.orase/assets/143128512/2f9be217-bc00-4776-96a0-81db9b8b70d5)
![48](https://github.com/peviitor-ro/ui.orase/assets/143128512/34fda4ff-0793-4ceb-a057-3168981cae49)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
