### ISSUE TITLE
”C.A. Rosetti” is listed in the drop-down menu

### ISSUE THREAD

**Issue by bogi1492** [peviitor-ro/ui.orase#6105]
**Description:** 
"C.A. Rosetti" is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

**Precondition:**
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 6105
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: ”C.A. Rosetti” is listed in the drop-down menu
[#6105](https://github.com/peviitor-ro/ui.orase/issues/6105)

Expected results:
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "**Sat** C.A. Rosetti, **TULCEA** (C.A. Rosetti)"

Actual results:
TC is missing.

**Comment by bogi1492** [comment]
>**Step 1**
Type "C.A. Rosetti" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** C.A. Rosetti, **TULCEA**".
