### ISSUE TITLE
"Bilca" is listed in the drop-down menu.

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/ui.orase#6154]
Description:
"Bilca" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 6154
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: "Bilca" is listed in the drop-down menu.
[#6154](https://github.com/peviitor-ro/ui.orase/issues/6154)

F1 -
Expected results:
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed :
"Bilca" is listed in the drop-down menu.
[#6154](https://github.com/peviitor-ro/ui.orase/issues/6154)

Actual results :
TC is missing.

**Comment by Elena1303996** [comment]
>**Step 1**
Type "Bilca" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Bilca, **SUCEAVA**".
