### ISSUE TITLE
"BUZIAȘ" is lised in the drop-down menu

### ISSUE THREAD

**Issue by TaniaR33** [peviitor-ro/ui.orase#6277]
Description:
"BUZIAȘ" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by TaniaR33** [comment]
>**Step 1**
Write in the search bar "BUZIAȘ.

**Expected results**
The location is listed in the drop-down menu as "Oraș  BUZIAȘ , TIMIȘ.

**Comment by Cristian-Emil** [comment]
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/552cf3ef-ed57-4ed8-bcaa-04a02bd8b00b)
