### ISSUE TITLE
"Bacova" is listed in the drop-down menu

### ISSUE THREAD

**Issue by TaniaR33** [peviitor-ro/ui.orase#6284]
Description: 
When user writes "Bacova" , the location appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by TaniaR33** [comment]
> **Step 1**
Write in the search bar "Bacova"

**Expected results** 
The location appears in the drop-down menu as "Bacova, TIMIȘ (BUZIAȘ)"

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 6284
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: "Bacova" is listed in the drop-down menu
[#6284](https://github.com/peviitor-ro/ui.orase/issues/6284)

Expected results:
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
STEP1
The link to the law is displayed :
"**Sat** Bacova, **TIMIȘ** (BUZIAȘ)" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Actual results:
Is requested to be displaye: "Bacova, TIMIȘ (BUZIAȘ)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/9a1179c1-ce09-4a28-a0ad-c73501dd7296)
