### ISSUE TITLE
"Cebza", "Macedonia", "Obad ", "Petroman" are listed in the drop down menu

### ISSUE THREAD

**Issue by TaniaR33** [peviitor-ro/ui.orase#6285]
Description: 
When user writes "Cebza", "Macedonia", "Obad" and  "Petroman" the locations appear in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by TaniaR33** [comment]
> **Step 1**
Write in the search bar "Cebza"

**Expected results** 
The location appears in the drop-down menu as "Cebza, TIMIȘ (CIACOVA)"

**Comment by TaniaR33** [comment]
> **Step 2**
Write in the search bar "Macedonia"

**Expected results** 
The location appears in the drop-down menu as "Macedonia", TIMIȘ (CIACOVA)

**Comment by TaniaR33** [comment]
> **Step 3**
Write in the search bar "Izbita"

**Expected results** 
The location appears in the drop-down menu as "Obad ", TIMIȘ (CIACOVA)"

**Comment by TaniaR33** [comment]
> **Step 4**
Write in the search bar "Petroman"

**Expected results** 
The location appears in the drop-down menu as "Petroman", TIMIȘ (CIACOVA)

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 6285
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC: "Cebza", "Macedonia", "Obad ", "Petroman" are listed in the drop down menu
[#6285](https://github.com/peviitor-ro/ui.orase/issues/6285)


Expected results:
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
**STEP1**
The link to the law is displayed :
"**Sat** Cebza, **TIMIȘ** (CIACOVA)" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Actusal results:
Is requested to be displayed:  "Cebza, TIMIȘ (CIACOVA)"
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/224bfdf2-5cf9-462d-a854-07e07b988288)


**STEP2**
The link to the law is displayed :
"**Sat** Macedonia, **TIMIȘ** (CIACOVA)" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Actusal results:
Is requested to be displayed:  "Macedonia, TIMIȘ (CIACOVA)"


**STEP3**
The link to the law is displayed :
"**Sat** Petroman, **TIMIȘ** (CIACOVA)" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Actusal results:
Is requested to be displayed:  "Petroman, TIMIȘ (CIACOVA)"



**STEP4**
The link to the law is displayed :
"**Sat** Obad, **TIMIȘ** (CIACOVA)" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Actusal results:
Is requested to be displayed:  "Obad ", TIMIȘ (CIACOVA)"
