### ISSUE TITLE
Câmpuri De Sus, Hunedoara (Gurasada) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#63]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Câmpuri De Sus" in the search bar
3. Select Câmpuri De Sus, Hunedoara (Gurasada) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![49](https://github.com/peviitor-ro/ui.orase/assets/143128512/e1883573-7ddb-453c-be8e-83ca54864eeb)
![50](https://github.com/peviitor-ro/ui.orase/assets/143128512/cc489dfc-58c7-4bb0-b7ad-11e6813bc330)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
