### ISSUE TITLE
"Poiana Blenchii" , "Fălcușa" , "Gostila" , "Măgura" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#6303]
**Description:**
The villages are listed in the drop-down menu alongside its corresponding county and city, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions:**  the  [website](https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by Catalinay** [comment]
> Step 1
> Write in the search bar "Poiana Blenchii"

Expected results
The location appears in the drop-down menu as "Sat Poiana Blenchii, SĂLAJ (Poiana Blenchii)"

**Comment by Catalinay** [comment]
> Step 2
> Write in the search bar "Fălcușa"

Expected results
The location appears in the drop-down menu as "Sat Fălcușai, SĂLAJ (Poiana Blenchii)"

**Comment by Catalinay** [comment]
> Step 3
> Write in the search bar "Gostila"

Expected results
The location appears in the drop-down menu as "Sat Gostila, SĂLAJ (Poiana Blenchii)"

**Comment by Catalinay** [comment]
> Step 4
> Write in the search bar "Măgura"

Expected results
The location appears in the drop-down menu as "Sat Măgura, SĂLAJ (Poiana Blenchii)"

**Comment by CristinaVoicu** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Firefox version 125
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

   1. Check TC: "Poiana Blenchii" , "Fălcușa" , "Gostila" , "Măgura" are listed in the drop-down menu
[#6303](https://github.com/peviitor-ro/ui.orase/issues/6303)
    2. Open URL in browser.
    3. Type "Fălcușai" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Fălcușai, SĂLAJ (Poiana Blenchii)".

ACTUAL RESULTS:
 "Sat Fălcușai, SĂLAJ (Poiana Blenchii)" is missing in the drop-down menu. The correct location is "Sat Fălcușa, SĂLAJ (Poiana Blenchii)"



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/debcea94-dc12-4de1-bf11-56bd426576df)



![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/d3d340ab-ea16-4f68-8570-df3ea3b5a09e)

**Comment by Catalinay** [comment]
Fixed, poti retesta!

**Comment by AdelinaGuliman** [comment]
@CristinaVoicu **the expected result is "Sat Fălcușa, SĂLAJ (Poiana Blenchii)", not "Fălcușai"
Pls retest!**



![Image](https://github.com/peviitor-ro/ui.orase/assets/137428958/d4870e96-7f37-41c3-88f3-2000f1da3339)
![Image](https://github.com/peviitor-ro/ui.orase/assets/137428958/f5f4f62e-7d7e-49e2-b63c-2a974240d674)
![Image](https://github.com/peviitor-ro/ui.orase/assets/137428958/178d59a6-662d-427b-9a2b-05b7d8f4d2c9)

**Comment by CristinaVoicu** [comment]
ok
