### ISSUE TITLE
"Scorțeni", "Bordenii Mari", "Bordenii Mici", "Mislea" and "Sârca" villages are listed in the drop-down menu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#6388]
The villages are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>**Step 1**
Type "Scorțeni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Scorțeni, PRAHOVA (Scorțeni)".

**Comment by DeedeeDL** [comment]
>**Step 2**
Type "Bordenii Mari" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Bordenii Mari, PRAHOVA (Scorțeni)".

**Comment by DeedeeDL** [comment]
>**Step 3**
Type "Bordenii Mici" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Bordenii Mici, PRAHOVA (Scorțeni)".

**Comment by DeedeeDL** [comment]
>**Step 4**
Type "Mislea" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Mislea, PRAHOVA (Scorțeni)".

**Comment by DeedeeDL** [comment]
>**Step 5**
Type "Sârca" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Sârca, PRAHOVA (Scorțeni)".

**Comment by CristinaVoicu** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Firefox version 125
Device: Laptop
OS: Windows 10 

STEPS TO REPRODUCE:
1. Check TC: "Scorțeni", "Bordenii Mari", "Bordenii Mici", "Mislea" and "Sârca" villages are listed in the drop-down menu
[#6388](https://github.com/peviitor-ro/ui.orase/issues/6388)
2. Open URL in browser.
3. Type "Sârca" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Sârca, PRAHOVA (Scorțeni)".

ACTUAL RESULTS:
"Sat Sârca, PRAHOVA (Scorțeni)" is missing in the drop-down menu.

![Image](https://github.com/peviitor-ro/ui.orase/assets/159782419/5a545d3c-3532-45b6-9540-d5a7c72ecf66)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi!

**Comment by AdelinaGuliman** [comment]
@CristinaVoicu **retest pls!**

**Comment by CristinaVoicu** [comment]
Retested, ok!
