### ISSUE TITLE
Hângănești (with diacritics) - Does not appears in the drop-down menu

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#64]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: MacOS

STEPS TO REPRODUCE:
1. Type "Hângănești" in the search bar (with diacritics)

EXPECTED RESULTS:
1. "Hângănești, Bacău (Brusturoasa)" appears in the drop-down menu
2. I can choose the "Hângănești, Bacău (Brusturoasa)" from the list

ACTUAL RESULTS:
1. "Hângănești, Bacău (Brusturoasa)" does not appears in the drop-down menu
2. I can not choose the "Hângănești, Bacău (Brusturoasa)" from the list

<img width="494" alt="Screenshot at Jan 30 13-23-21" src="https://github.com/peviitor-ro/ui.orase/assets/137428958/13dcf6de-6efd-4d50-9c8c-b78a69f7c099">
<img width="221" alt="Screenshot at Jan 30 13-23-01" src="https://github.com/peviitor-ro/ui.orase/assets/137428958/0a428f26-fa73-4de1-b1bf-a27abf27a8e2">
<img width="446" alt="Screenshot at Jan 30 13-22-52" src="https://github.com/peviitor-ro/ui.orase/assets/137428958/8ff19a93-9d99-4633-9970-91a2dde1f79d">

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
