### ISSUE TITLE
"Poseștii-Pământeni" , "Bodești", "Merdeala", "Nucșoara de Jos", "Nucșoara de Sus", "Poseștii-Ungureni ", "Tulburea-Văleni", "Târlești", "Valea Plopului", "Valea Screzii" and "Valea Stupinii" villages are listed in the drop-down menu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#6459]
The villages are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Preconditions : the website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by DeedeeDL** [comment]
>**Step 1**
Type "Poseștii-Pământeni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Poseștii-Pământeni, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 2**
Type "Bodești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Bodești, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 3**
Type "Merdeala" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat**Merdeala, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 4**
Type "Nucșoara de Jos" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat**Nucșoara de Jos, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 5**
Type "Nucșoara de Sus" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Nucșoara de Sus, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 6**
Type "Poseștii-Ungureni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Poseștii-Ungureni, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 7**
Type "Tulburea-Văleni" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Tulburea-Văleni, PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 8**
Type "Târlești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Târlești,  PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 10**
Type "Valea Screzii" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Valea Screzii,  PRAHOVA (Posești)".

**Comment by DeedeeDL** [comment]
>**Step 11**
Type "Valea Stupinii" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Sat** Valea Stupinii,  PRAHOVA (Posești)".

**Comment by AndraMvr** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome version 125
Device: Desktop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Check TC: ""Poseștii-Pământeni" , "Bodești", "Merdeala", "Nucșoara de Jos", "Nucșoara de Sus", "Poseștii-Ungureni ", "Tulburea-Văleni", "Târlești", "Valea Plopului", "Valea Screzii" and "Valea Stupinii" villages are listed in the drop-down menu
https://github.com/peviitor-ro/ui.orase/issues/6459
Open URL in browser.
Type "Valea Stupinii" in the search bar.
EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Valea Stupinii, PRAHOVA (Posești)"..

ACTUAL RESULTS:
"Sat Valea Stupinii, PRAHOVA (Posești)". is missing in the drop-down menu.




![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/61720e81-2f46-48c6-b0a8-9283f5dbf116)

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x please add this location 



![Image](https://github.com/peviitor-ro/ui.orase/assets/137428958/ed1026ba-eeee-4f56-bf13-c418012cfe38)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi!
