### ISSUE TITLE
Lăpugiu De Jos/Lăpugiu De Sus, Hunedoara - Are not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#65]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Lăpugiu De Jos" in the search bar (/Lăpugiu De Sus)
3. Select Lăpugiu De Jos, Hunedoara from the list (/Lăpugiu De Sus, Hunedoara (Lăpugiu De Jos))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![51](https://github.com/peviitor-ro/ui.orase/assets/143128512/76a2fb70-8026-4fe1-997b-8f6a1965eacc)
![52](https://github.com/peviitor-ro/ui.orase/assets/143128512/17a2672e-70df-4669-ae7a-08ba397c37b8)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by danielastanculesc** [comment]
Mai trebuie modificat si la localitatea de care apartine, adica ce este in paranteza.
![59](https://github.com/peviitor-ro/ui.orase/assets/143128512/d3beab2d-0144-4660-9a51-943fae98fc92)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
