### ISSUE TITLE
Lunca Cernii De Jos/Lunca Cernii De Sus, Hunedoara - Are not written correctly 

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#66]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Lunca Cernii De Jos" in the search bar (/Lunca Cernii De Sus)
3. Select Lunca Cernii De Jos, Hunedoara from the list (/Lunca Cernii De Sus, Hunedoara (Lunca Cernii De Jos))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![53](https://github.com/peviitor-ro/ui.orase/assets/143128512/be1bd4b2-45e7-40f7-b3e5-99c4ad307583)
![54](https://github.com/peviitor-ro/ui.orase/assets/143128512/90a61dfd-8953-4194-9a02-614f6d87cce3)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
