### ISSUE TITLE
"Scăești" , "Valea lui Pătru" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#6634]
**Description:**
The villages are listed in the drop-down menu alongside its corresponding county and city, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions:**  the  [website](https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by Catalinay** [comment]
> Step 1
> Write in the search bar "Scăești"

Expected results
The location appears in the drop-down menu as "Sat Scăești, SĂLAJ (Scăești)"

**Comment by Catalinay** [comment]
> Step 2
> Write in the search bar "Valea lui Pătru"

Expected results
The location appears in the drop-down menu as "Sat Valea lui Pătru, SĂLAJ (Scăești)"

**Comment by aplugaru** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
DEVICE: LAPTOP
OS: Windows

STEPS TO REPRODUCE:

Open url in browser
1. Write in the search bar "Scăești"
2. 2. Write in the search bar "Valea lui Pătru"

EXPECTED RESULTS:
1.The location appears in the drop-down menu as "Sat Scăești, SĂLAJ (Scăești)"
2.The location appears in the drop-down menu as "Sat Valea lui Pătru, SĂLAJ (Scăești)"

ACTUAL RESULTS:
1."Sat Scăești, SĂLAJ (Scăești)" doesn't exist in the drip-down menu
2."Sat Valea lui Pătru, SĂLAJ (Scăești)" doesn't exist in the drip-down menu



![Image](https://github.com/peviitor-ro/ui.orase/assets/134128972/e6ab31d3-8bba-4301-9d2c-5c0dff0b7ee6)




![Image](https://github.com/peviitor-ro/ui.orase/assets/134128972/0257ceea-2402-4cab-b208-72831fdec31e)
