### ISSUE TITLE
"Rasnicu Oghian" , "Țiu" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#6635]
**Description:**
The villages are listed in the drop-down menu alongside its corresponding county and city, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions:**  the  [website](https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by Catalinay** [comment]
> Step 1
> Write in the search bar "Rasnicu Oghian"

Expected results
The location appears in the drop-down menu as "Sat Rasnicu Oghian, SĂLAJ (Cernătești)"

**Comment by Catalinay** [comment]
> Step 2
> Write in the search bar "Țiu"

Expected results
The location appears in the drop-down menu as "Sat Țiu, SĂLAJ (Cernătești)"

**Comment by aplugaru** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
BROWSER: CHROME
DEVICE: laptop
OS: Windows

STEPS TO REPRODUCE:
1.Write in the search bar "Rasnicu Oghian"
2.Write in the search bar "Țiu"

EXPECTED RESULTS:
1. The location appears in the drop-down menu as "Sat Rasnicu Oghian, SĂLAJ (Cernătești)"
2. The location appears in the drop-down menu as "Sat Țiu, SĂLAJ (Cernătești)"

ACTUAL RESULTS:
1. "Sat Rasnicu Oghian, SĂLAJ (Cernătești)" doesn't exist in the drop-down menu
2. "Sat Țiu, SĂLAJ (Cernătești)"  doesn't exist in the drop-down menu




![Image](https://github.com/peviitor-ro/ui.orase/assets/134128972/793ef47e-b678-488d-a62f-dae980fbf0f6)



![Image](https://github.com/peviitor-ro/ui.orase/assets/134128972/0743ced3-5f89-4f4b-8164-9f0480a54954)
