### ISSUE TITLE
Luncoiu De Jos, Hunedoara/Luncoiu De Sus, Hunedoara - Are not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#67]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Luncoiu De Jos" in the search bar (/Luncoiu De Sus)
3. Select Luncoiu De Jos, Hunedoara from the list (/Luncoiu  De Sus, Hunedoara (Luncoiu De Jos))

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![55](https://github.com/peviitor-ro/ui.orase/assets/143128512/5692144f-8e99-4e44-a16d-db170a3befe7)
![56](https://github.com/peviitor-ro/ui.orase/assets/143128512/b6ba4fe5-3d68-42d5-9dc0-6942fa496cc2)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by danielastanculesc** [comment]
Mai trebuie modificat si la localitatea de care apartine, adica ce este in paranteza,
![57](https://github.com/peviitor-ro/ui.orase/assets/143128512/702e1815-5d90-4acf-994f-246452102d7a)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
