### ISSUE TITLE
"Bărăști" is listed in the drop-down menu

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#6887]
Description:
When user writes "Bărăști" the location appears in the drop-down menu next to the comune and the county witch is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by SimonaNemtanu** [comment]
Step 1
Write in the search bar "Bărăști"

Expected results
The location appears in the drop-down menu as "Comuna Bărăști, OLT"

**Comment by AndraMvr** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome version 125
Device: Desktop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Check TC: "Bărăști" is listed in the drop-down menu
[#6887](https://github.com/peviitor-ro/ui.orase/issues/6887)
Open URL in browser.
Type "Bărăști" in the search bar.

EXPECTED RESULTS:
The location appears in the drop-down menu as "Comuna Bărăști, OLT"

ACTUAL RESULTS:
"Comuna Bărăști, OLT" is missing in the drop-down menu.

![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/48237398-3eae-47a8-8677-ce2e3b8ee011)

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x add this location pls

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
