### ISSUE TITLE
"Bărăștii de Vede", "Bărăștii de Cepturi", "Boroești", "Ciocănești", "Lăzărești", "Mereni", "Moțoești", "Popești" are listed in the drop-down menu

### ISSUE THREAD

**Issue by SimonaNemtanu** [peviitor-ro/ui.orase#6888]
Description:
When user writes "Bărăștii de Vede", "Bărăștii de Cepturi", "Boroești", "Ciocănești", "Lăzărești", "Mereni", "Moțoești" and "Popești" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by SimonaNemtanu** [comment]
Step 1
Write in the search bar "Bărăștii de Vede"

Expected results
The location appears in the drop-down menu as "Sat Bărăștii de Vede, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 2
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 3
Write in the search bar "Bărăștii de Cepturi"

Expected results
The location appears in the drop-down menu as "Sat Bărăștii de Cepturi, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 4
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 5
Write in the search bar "Boroești"

Expected results
The location appears in the drop-down menu as "Sat Boroești , OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 6
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 7
Write in the search bar "Ciocănești"

Expected results
The location appears in the drop-down menu as "Sat Ciocănești, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 8
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 9
Write in the search bar "Lăzărești"

Expected results
The location appears in the drop-down menu as "Sat Lăzărești, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 10
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 11
Write in the search bar "Mereni"

Expected results
The location appears in the drop-down menu as "Sat Mereni, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 12
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 13
Write in the search bar "Moțoești"

Expected results
The location appears in the drop-down menu as "Sat Moțoești, OLT (Bărăști)"

**Comment by SimonaNemtanu** [comment]
Step 14
Press "x" button.

Expected results
The location was deleted from the search bar.

**Comment by SimonaNemtanu** [comment]
Step 15
Write in the search bar "Popești"

Expected results
The location appears in the drop-down menu as "Sat Popești, OLT (Bărăști)"

**Comment by AndraMvr** [comment]
ENVIRONMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome version 125
Device: Desktop
OS: Windows 10 Pro

STEPS TO REPRODUCE:

Check TC: "Bărăștii de Vede", "Bărăștii de Cepturi", "Boroești", "Ciocănești", "Lăzărești", "Mereni", "Moțoești", "Popești" are listed in the drop-down menu
[#6888](https://github.com/peviitor-ro/ui.orase/issues/6888)
Open URL in browser.
Type "Sat Bărăștii de Vede" in the search bar.
EXPECTED RESULTS:
The location appears in the drop-down menu as "Sat Bărăștii de Vede, OLT (Bărăști)"
ACTUAL RESULTS:
"Sat Bărăștii de Vede, OLT (Bărăști)"  is listed as  "Comuna Bărăștii de Vede, OLT (Bărăști)" Or "Oras Bărăștii de Vede, OLT (Bărăști de Vede)"


![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/e447a562-e98f-4146-99aa-916d10e5c14c)



![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/bedbbf04-b660-4a89-91aa-bf1d5062d558)

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x pls fix this location

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
