### ISSUE TITLE
"Andrășești" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/ui.orase#6964]
Description:
"Andrășești" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by Elena1303996** [comment]
>**Step 1**
Type "Andrășești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Andrășești, **SUCEAVA**".

**Comment by Georgianaredenstein** [comment]
@Elena1303996 ''The location is listed in the drop-down menu as "Comuna Andrășești, SUCEAVA". does not appear for the county Suceava

![Image](https://github.com/peviitor-ro/ui.orase/assets/124400281/0ff0d142-1818-4451-b27a-9e157ed92426)

**Comment by Elena1303996** [comment]
>**Step 1**
Type "Andrășești" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Andrășești, **IALOMIȚA**".

**Comment by Georgianaredenstein** [comment]
@Elena1303996  now it's ok !
