### ISSUE TITLE
"Balaciu" is listed in the drop-down menu

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/ui.orase#7040]
Description:
"Balaciu" is listed in the drop-down menu alongside its corresponding county according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by MarinaCosmina** [comment]
Lipsa 'Step 1 si Expected results' din test case

**Comment by Elena1303996** [comment]
>**Step 1**
Type "Balaciu" in the search bar.

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Balaciu, **IALOMIȚA**".

**Comment by Elena1303996** [comment]
@MarinaCosmina , retest, please! thank you!
