### ISSUE TITLE
" Covăsinț" are villages in " Covăsinț" common, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#730]

**Comment by chiparca81** [comment]
**Precondition**

Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by chiparca81** [comment]
**Steps** 

Write "Covăsinț"

**Expected result**

In the drop down menu you find "Covăsinț, ARAD(Covăsinț)"

**Test Data**

Covăsinț

**Comment by AndraADM** [comment]
browser: Opera
device: laptop
OS: Windos 10

Steps to reproduce:
1. Open the [website](https://peviitor-ro.github.io/ui.orase/)
2. Type in the search bar  "Covăsinț"

Expected results:
1. The location is listed in the drop down menu as "Covăsinț, ARAD(Covăsinț)"

Actual result:
1. The location is listed in the drop down menu as  "Covăsinț, ARAD"





![Image](https://github.com/peviitor-ro/ui.orase/assets/142739627/dd904043-0fbe-49ed-9846-954a86cbb96e)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi.
