### ISSUE TITLE
"Dorobanți" are villages in "Dorobanți" common, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#737]

**Comment by chiparca81** [comment]
**Precondition**

Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by AndraADM** [comment]
environment: test
browse: Opera
device:laptop
OS: Windows 10

Steps to reproduce:
1.Open the [website](https://peviitor-ro.github.io/ui.orase/)
2. Type in the search bar  "Dorobanți"

Expected results:
1.The location is listed in the drop down menu as  "Dorobanți, ARAD(Dorobanți)"

Actual result:
1. The location is listed in the drop  down menu as "Dorobanți, ARAD"



![Image](https://github.com/peviitor-ro/ui.orase/assets/142739627/f17aeed7-c773-44cf-9239-49d26fd903b1)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi.
