### ISSUE TITLE
"Bonțești, Dulcele, Feniș, Honțișor, Iosaș, Mustești, Pescari, Valea Mare, Zimbru" are villages in "Gurahonț" common, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#743]

**Comment by chiparca81** [comment]
**Precondition**

Empty the search bar after every step

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by chiparca81** [comment]
**Steps 2** 

Write "Bonțești"

**Expected result**

In the drop down menu you find "Bonțești, ARAD( Gurahonț)"

**Test Data**

Bonțești

**Comment by chiparca81** [comment]
**Steps 4** 

Write " Feniș"

**Expected result**

In the drop down menu you find " Feniș, ARAD(Gurahonț)"

**Test Data**

 Feniș

**Comment by chiparca81** [comment]
**Steps 5** 

Write "Honțișor"

**Expected result**

In the drop down menu you find "Honțișor, ARAD(Gurahonț)"

**Test Data**

Honțișor

**Comment by chiparca81** [comment]
**Steps 6** 

Write "Iosaș"

**Expected result**

In the drop down menu you find "Iosaș, ARAD(Gurahonț)"

**Test Data**

Iosaș

**Comment by chiparca81** [comment]
**Steps 7** 

Write "Mustești"

**Expected result**

In the drop down menu you find " Mustești, ARAD(Gurahonț)"

**Test Data**

 Mustești

**Comment by chiparca81** [comment]
**Steps 8** 

Write "Pescari"

**Expected result**

In the drop down menu you find "Pescari, ARAD()"

**Test Data**

Pescari

**Comment by chiparca81** [comment]
**Steps 9** 

Write "Valea Mare"

**Expected result**

In the drop down menu you find "Valea Mare, ARAD(Gurahonț()"

**Test Data**

Valea Mare

**Comment by chiparca81** [comment]
**Steps 10** 

Write "Zimbru"

**Expected result**

In the drop down menu you find "Zimbru, ARAD(Gurahonț)"

**Test Data**

Zimbru

**Comment by AdinaIT** [comment]
The county assigness these localities is ARAD, not ALBA
I changed label
