### ISSUE TITLE
"Perișani " , "Băiașu " , "Mlăceni " , "Podeni " , "Poiana" , "Pripoare " , "Spinu " , "Surdoiu" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Catalinay** [peviitor-ro/ui.orase#7475]
The villages are listed in the drop-down menu alongside its corresponding county and city, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions :** the  [website](https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by Catalinay** [comment]
> Step 1
> Write in the search bar "Perișani "

Expected results
The location appears in the drop-down menu as "Sat Perișani , VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 3
> Write in the search bar "Mlăceni "

Expected results
The location appears in the drop-down menu as "Sat Mlăceni , VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 4
> Write in the search bar "Podeni "

Expected results
The location appears in the drop-down menu as "Sat Podeni , VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 5
> Write in the search bar "Poiana"

Expected results
The location appears in the drop-down menu as "Sat Poiana, VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 6
> Write in the search bar "Pripoare "

Expected results
The location appears in the drop-down menu as "Sat Pripoare , VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 7
> Write in the search bar "Spinu "

Expected results
The location appears in the drop-down menu as "Sat Spinu , VÂLCEA (Surdoiu)"

**Comment by Catalinay** [comment]
> Step 8
> Write in the search bar "Surdoiu"

Expected results
The location appears in the drop-down menu as "Sat Surdoiu, VÂLCEA (Surdoiu)"

**Comment by AndraMvr** [comment]
The problem is in the description of the test cases. The name of the commune is "Perișani", not Surdoiu.



![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/ecc67919-8e0b-44c4-b3b2-ff4056e9c01b)


![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/53117f9c-0125-4c86-9eee-6836ec8ad232)



![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/e1e79a77-cd90-4512-9cf7-12b31fb1d107)

**Comment by Catalinay** [comment]
Fixed, please retest!
