### ISSUE TITLE
"Vlădila", "Frăsinet-Gară" and "Vlădila Nouă" are listed in the drop-down menu

### ISSUE THREAD

**Issue by Elena1303996** [peviitor-ro/ui.orase#7536]
Description: 
When user writes ”Vlădila”, "Frăsinet-Gară" and "Vlădila Nouă" the locations appear in the drop-down menu next to the comune and the county which is a part according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running. After every step delete the text you typed from the search bar.

**Comment by Elena1303996** [comment]
>**Step 1**
Write in the search bar "Vlădila".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Vlădila **OLT** (Vlădila)".

**Comment by Elena1303996** [comment]
>**Step 2**
Write in the search bar "Frăsinet-Gară".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Frăsinet-Gară **OLT** (Vlădila)".

**Comment by Elena1303996** [comment]
>**Step 3**
Write in the search bar "Vlădila Nouă".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Vlădila Nouă **OLT** (Vlădila)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 4104
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC["Vlădila", "Frăsinet-Gară" and "Vlădila Nouă" are listed in the drop-down menu
[#7536](https://github.com/peviitor-ro/ui.orase/issues/7536)

Expected results:
Precondition (request):
The link to the law is displayed : "Sat Frăsinet-Gară OLT (Vlădila))"

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/97a25a3c-ddb8-47d8-a06e-b2080b3935f1)


Actual result (displayed):
In "https://peviitor-ro.github.io/ui.orase/" is missing:

![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/8faf8827-961c-4705-b497-6e786909a06b)

**Comment by AdelinaGuliman** [comment]
@Cristian-Emil please retest

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi!
