### ISSUE TITLE
"Beba Veche" is listed in the drop-down menu

### ISSUE THREAD

**Issue by TaniaR33** [peviitor-ro/ui.orase#7544]
**Description**:
The commune is listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions**: 
The website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by TaniaR33** [comment]
>**Step 1**
Write in the search bar "Banloc".

**Expected results**
The location is listed in the drop-down menu as "**Comuna** Beba Veche, **TIMIȘ** ".

**Comment by AndraMvr** [comment]
The Bug is in the description of the test case, not the test case itself.

The name should have been Beba Veche.

![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/ea9c1dce-b818-404e-89cd-c1d22fb74d4f)

**Comment by AdelinaGuliman** [comment]
@TaniaR33 please correct this test case
