### ISSUE TITLE
" Beba Veche". "Cherestur", "Pordeanu" are listed in the drop-down menu

### ISSUE THREAD

**Issue by TaniaR33** [peviitor-ro/ui.orase#7545]
**Description**:
The villages are listed in the drop-down menu alongside its corresponding county and commune, according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189)

**Preconditions**: 
The website (https://peviitor-ro.github.io/ui.orase/) is up and runing. After every step delete the text you typed from the search bar.

**Comment by TaniaR33** [comment]
>**Step 1**
Write in the search bar "Beba Veche".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Beba Veche, **TIMIȘ** (Beba Veche)".

**Comment by TaniaR33** [comment]
>**Step  2**
Write in the search bar "Beba Veche".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Cherestur, **TIMIȘ** (Beba Veche)".

**Comment by TaniaR33** [comment]
>**Step 3**
Write in the search bar "Beba Veche".

**Expected results**
The location is listed in the drop-down menu as "**Sat** Pordeanu, **TIMIȘ** (Beba Veche)".

**Comment by AndraMvr** [comment]
The fail is in the description of the steps to reproduce from the test cases. 

The names of the villages to be searched are wrong.



![Image](https://github.com/peviitor-ro/ui.orase/assets/102318954/7ae09ca5-787e-46df-9b1c-8bf98a48f003)

**Comment by AdelinaGuliman** [comment]
@TaniaR33 please correct this test case

**Comment by TaniaR33** [comment]
Gata, le poți re testa

lun., 3 iun. 2024, 17:43 Guliman Adelina-Ioana ***@***.***> a
scris:
