### ISSUE TITLE
"Burcioaia" is listed in the drop-down menu

### ISSUE THREAD

**Issue by DeedeeDL** [peviitor-ro/ui.orase#7559]
Description:
When user writes "Burcioaia" the location appears in the drop-down menu according to the [law](https://legislatie.just.ro/Public/DetaliiDocument/189).

Precondition:
The [website](https://peviitor-ro.github.io/ui.orase/) is up an running.

**Comment by DeedeeDL** [comment]
> **Step 1**
Write in the search bar "Burcioaia"

**Expected results** 
The location appears in the drop-down menu as "**Sat** Burcioaia, **Vrancea** (Adjud)".

**Comment by Cristian-Emil** [comment]
Environment: Run Tests - 7559
Browser: Chrome 123
OS: Windows 10

Steps to reproduce:
1 Open the [@Adelina](https://github.com/Adelina) Guliman Test case ui.orase
2. Check TC["Burcioaia" is listed in the drop-down menu](https://github.com/peviitor-ro/ui.orase/issues/7559)
#7559

Expected results:
Precondition (request):
The website link (https://peviitor-ro.github.io/ui.orase/) is up and running
The link to the law is displayed : "Sat Burcioaia, Vrancea (Adjud)"

Actual result (displayed):
In "https://peviitor-ro.github.io/ui.orase/" is not valid :
![Image](https://github.com/peviitor-ro/ui.orase/assets/124686433/3496356f-6783-4f7f-90a1-e0ecee735e5c)

**Comment by AdelinaGuliman** [comment]
@OvidiuAl3x pls add this location

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi
