### ISSUE TITLE
" Avram Iancu, Groși, Lazuri, Măgulicea, Mermești, Poiana, Vidra" are villages in "Vârfurile " common, "ARAD" county

### ISSUE THREAD

**Issue by chiparca81** [peviitor-ro/ui.orase#833]

**Comment by chiparca81** [comment]
**Steps 1**

Acces to the link https://peviitor-ro.github.io/ui.orase/

**Expected result**

The page opens

**Comment by chiparca81** [comment]
**Steps 2** 

Write "Avram Iancu"

**Expected result**

In the drop down menu you find "Avram Iancu, ARAD(Vârfurile)"

**Test Data**

Avram Iancu

**Comment by chiparca81** [comment]
**Steps 3** 

Write " Groși "

**Expected result**

In the drop down menu you find " Groși , ARAD(Vârfurile)"

**Test Data**

 Groși

**Comment by chiparca81** [comment]
**Steps 4** 

Write " Lazuri "

**Expected result**

In the drop down menu you find " Lazuri , ARAD((Vârfurile)"

**Test Data**

 Lazuri

**Comment by chiparca81** [comment]
**Steps 5** 

Write "Măgulicea"

**Expected result**

In the drop down menu you find "Măgulicea, ARAD(Vârfurile)"

**Test Data**

Măgulicea

**Comment by chiparca81** [comment]
**Steps 6** 

Write "Mermești "

**Expected result**

In the drop down menu you find "Mermești , ARAD(Vârfurile)"

**Test Data**

Mermești

**Comment by chiparca81** [comment]
**Steps 7** 

Write "Vârfurile"

**Expected result**

In the drop down menu you find "Vârfurile, ARAD(Vârfurile)"

**Test Data**

Vârfurile

**Comment by chiparca81** [comment]
**Steps 8** 

Write "Vidra"

**Expected result**

In the drop down menu you find "Vidra, ARAD(Vârfurile)"

**Test Data**

Vidra

**Comment by OvidiuAl3x** [comment]
Fixed! Poti sa retestezi

**Comment by CristinaVoicu** [comment]
ok
