### ISSUE TITLE
Voiteștii din Vale/Deal, Gorj (Bălănești) - are not written correctly

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/ui.orase#86]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Voiteștii" in the search bar
3. Looking after "Voiteștii din Vale/ Deal, Gorj (Bălănești)".

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/af3a2c64-0604-49a4-af59-33379d1b329a)
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/a24a7774-e0c1-4caa-bb61-d9be70850736)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by Aniod01** [comment]
Retestetd.
