### ISSUE TITLE
Menții din Dos, Gorj (Borăscu) - is not written correctly

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/ui.orase#87]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Menții din Dos" in the search bar
3. Looking after "Menții din Dos, Gorj (Borăscu)".

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/d60a2d55-b8fa-41c0-b6dd-77b45cd83b25)
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/38e9d484-cec0-421e-9c38-b3fbb439cf2f)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta

**Comment by Aniod01** [comment]
Retested.
