### ISSUE TITLE
Cotu Lui Ivan, Iași (Golăiești) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#88]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Cotu lui Ivan" in the search bar 
3. Select Cotu Lui Ivan, Iași (Golăiești) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![61](https://github.com/peviitor-ro/ui.orase/assets/143128512/f3c03aeb-05ff-4eb2-89a3-f7c0dfdadcac)
![62](https://github.com/peviitor-ro/ui.orase/assets/143128512/8f6f0155-5104-4f66-978d-1cc3a4933c75)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
