### ISSUE TITLE
Poiana Cu Cetate, Iași (Grajduri) - Is not written correctly

### ISSUE THREAD

**Issue by danielastanculesc** [peviitor-ro/ui.orase#89]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 7

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Poiana cu Cetate" in the search bar
3. Select Poiana Cu Cetate, Iași (Grajduri) from the list

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929

![63](https://github.com/peviitor-ro/ui.orase/assets/143128512/e132b266-dee8-43be-a0f3-d5e97b73909d)
![64](https://github.com/peviitor-ro/ui.orase/assets/143128512/53d57db1-e37b-4366-bd2d-bd50883af1c3)

**Comment by OvidiuAl3x** [comment]
Fixed! Poti retesta
