### ISSUE TITLE
Pișteștii din Deal,  Gorj (Scoarța) - is not written correctly

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/ui.orase#96]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Pișteștii din Deal" in the search bar
3. Looking after "Pișteștii din Deal,  Gorj (Scoarța)".

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/77db32b5-3ae9-478c-911c-574c3d481463)

**Comment by OvidiuAl3x** [comment]
Fixed. Poti sa retestezi.
