### ISSUE TITLE
Alexandru Cel Bun, Neamț - is not written correctly

### ISSUE THREAD

**Issue by Aniod01** [peviitor-ro/ui.orase#97]
ENVIROMENT: ui.orase
URL: https://peviitor-ro.github.io/ui.orase/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open URL in browser
2. Type "Alexandru Cel Bun" in the search bar
3. Looking after "Alexandru Cel Bun, Neamț"

EXPECTED RESULTS:
The name of the locality written in the search bar is written correctly based off the law nr. 167/1929
https://legislatie.just.ro/Public/DetaliiDocument/189

ACTUAL RESULTS:
The name of the locality written in the search bar is not written correctly based off the law nr. 167/1929
![image](https://github.com/peviitor-ro/ui.orase/assets/63416053/e5e5e906-b667-43ab-af16-54bd3a352897)

**Comment by OvidiuAl3x** [comment]
Fixed. Poti sa retestezi.
