### ISSUE TITLE
System does not accept input containing special characters and symbols

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/ui.orase#99]
> Description: 
Special characters and symbols are not allowed.

> Preconditions:
The website is up and running.

**Comment by AdelinaGuliman** [comment]
Special characters must not be allowed


https://github.com/peviitor-ro/ui.orase/assets/137428958/ca8b9d8e-926e-48b6-8014-faf82686fdbd

**Comment by OvidiuAl3x** [comment]
Fixed. Poti sa retestezi.
